using System.Collections.Generic;

namespace Eliminated.Sim.Localization
{
    /// <summary>
    /// Lightweight localization: code-embedded string tables keyed by locale,
    /// with English fallback and {0}-style argument formatting. Pure C# so it is
    /// unit-tested headlessly and shared by the sim and the Unity client. The
    /// Unity Localization package can replace these tables later (Phase 7) without
    /// changing call sites — they all go through <see cref="Get"/>.
    ///
    /// Game names are keyed "game.&lt;GameId&gt;"; UI/Game-Master strings under
    /// "ui."/"gm.". en/es/fr are complete; de/pt/ja/ko/zh-Hans localize the most
    /// visible strings and fall back to English elsewhere (starter translations — a
    /// native pass refines them). Korean and Chinese matter for the genre this game
    /// homages, so the childhood-game names use their real local equivalents.
    /// </summary>
    public static class Loc
    {
        public const string Default = "en";
        public static string Locale = Default;

        public static readonly string[] Locales = { "en", "es", "fr", "de", "pt-BR", "ja", "ko", "zh-Hans" };

        public static void SetLocale(string locale)
        {
            Locale = _tables.ContainsKey(locale) ? locale : Default;
        }

        public static bool HasLocale(string locale) => _tables.ContainsKey(locale);

        /// <summary>Localized string for the current locale (English fallback),
        /// with optional {0}/{1} argument formatting.</summary>
        public static string Get(string key, params object[] args)
        {
            string s = Lookup(Locale, key) ?? Lookup(Default, key) ?? key;
            return args != null && args.Length > 0 ? string.Format(s, args) : s;
        }

        public static string GetIn(string locale, string key, params object[] args)
        {
            string s = Lookup(locale, key) ?? Lookup(Default, key) ?? key;
            return args != null && args.Length > 0 ? string.Format(s, args) : s;
        }

        private static string Lookup(string locale, string key)
            => _tables.TryGetValue(locale, out var t) && t.TryGetValue(key, out var v) ? v : null;

        private static readonly Dictionary<string, Dictionary<string, string>> _tables =
            new Dictionary<string, Dictionary<string, string>>
        {
            ["en"] = new Dictionary<string, string>
            {
                ["ui.title"] = "ELIMINATED",
                ["ui.tagline"] = "A wholesome party game where everyone dies.",
                ["ui.play_solo_casual"] = "Solo vs Bots — Casual",
                ["ui.play_solo_hardcore"] = "Solo vs Bots — Hardcore (last player standing)",
                ["ui.local_coop"] = "Local Co-op",
                ["ui.settings"] = "Settings",
                ["ui.quit"] = "Quit",
                ["ui.back_to_menu"] = "Back to Menu",
                ["ui.save_and_back"] = "Save & Back",
                ["ui.get_ready"] = "Get ready…",
                ["ui.reckoning"] = "The Reckoning",
                ["ui.series_over"] = "A Winner Has Been Decided",
                ["ui.marbles"] = "Marbles",
                ["ui.round"] = "Round {0}",
                ["gm.game_intro"] = "Game Master: Game {0} — {1}.",
                ["gm.room_intro"] = "The arena: {0}.",
                ["room.courtyard"] = "The Courtyard",
                ["room.neon"] = "Neon District",
                ["room.candy"] = "Candy Kingdom",
                ["room.toxic"] = "The Toxic Works",
                ["room.beach"] = "Sunny Shores",
                ["room.haunt"] = "Haunted Manor",
                ["gm.champion"] = "Game Master: {0} is the last player standing!",
                ["game.RedLight"] = "Red Light, Green Light",
                ["game.Tag"] = "Freeze Tag",
                ["game.Mingle"] = "Mingle",
                ["game.GlassBridge"] = "Glass Stepping Stones",
                ["game.TugOfWar"] = "Tug of War",
                ["game.RpsMinusOne"] = "RPS Minus One",
                ["game.JumpRope"] = "Killer Jump Rope",
                ["game.Boomerang"] = "Boomerang Brawl",
                ["game.Dodgeball"] = "Dodgeball",
                ["game.MusicalChairs"] = "Musical Chairs",
                ["game.PresentSwap"] = "Secret Santa Sabotage",
                ["game.PropHunt"] = "Prop Hunt",
                ["game.ChutesAndLadders"] = "Chutes & Ladders",
                ["game.SimonSays"] = "Simon Says",
                ["game.KeepyUppy"] = "Keepy Uppy",
                ["game.KingOfTheHill"] = "King of the Lava Islands",

                // ── UI chrome / navigation ──
                ["ui.back"] = "← Back",
                ["ui.play"] = "PLAY",
                ["ui.your_player"] = "Your Player",
                ["ui.choose_how"] = "CHOOSE HOW TO PLAY",
                ["ui.play_online"] = "Play Online",
                ["ui.solo_vs_bots"] = "Solo vs Bots",
                ["ui.local_coop_n"] = "Local Co-op — {0} players",
                ["ui.coop_needs_gamepad"] = "* Local Co-op needs a gamepad connected",
                ["ui.choose_difficulty"] = "{0}  ·  CHOOSE DIFFICULTY",
                ["ui.casual"] = "Casual",
                ["ui.hardcore"] = "Hardcore",
                ["ui.save"] = "Save",
                ["ui.saved"] = "Saved",
                ["nav.leaderboard"] = "Leaderboard",
                ["nav.how_to_play"] = "How to Play",
                ["nav.patch_notes"] = "Patch Notes",

                // ── Settings ──
                ["set.language"] = "Language:",
                ["set.colorblind"] = "Colorblind mode:",
                ["set.subtitles"] = "Captions / subtitles",
                ["set.reduce_motion"] = "Reduce flashing & screen shake",
                ["set.master_volume"] = "Master volume: {0}%",
                ["set.game_volume"] = "Game sound: {0}%",
                ["set.music_volume"] = "Background music: {0}%",
                ["set.music"] = "Music",
                ["set.remap"] = "Remap controls",
                ["set.credits"] = "Credits & licenses",
                ["set.grp_visual"] = "VISUAL",
                ["set.grp_audio"] = "AUDIO",
                ["cb.Normal"] = "Off",
                ["cb.RedGreen"] = "Red–Green",
                ["cb.BlueYellow"] = "Blue–Yellow",

                // ── Results / HUD ──
                ["res.safe"] = "SAFE",
                ["res.out"] = "OUT",
                ["res.you"] = "(YOU)",
                ["hud.countdown"] = "3 · 2 · 1 · GO!",
                ["hud.round_game"] = "Round {0} · {1}",
                ["hud.players_alive"] = "Players alive: {0}",
                ["hud.you_are"] = "You are #{0}",
                ["hud.hint_default"] = "WASD/Arrows to move.",
                ["hud.hint_redlight"] = "Run FORWARD on GREEN (hold W / D / →). FREEZE on RED.",
                ["hud.hint_tug"] = "MASH Space / Click to pull your team to victory!",
                ["hud.hint_boomerang"] = "Move (WASD) · Aim (mouse) · Throw (Click/Space) · Dash (Shift)",
                ["hud.hint_move_action"] = "WASD/Arrows move · Space action · Shift dash",
                ["hud.hint_dodgeball"] = "Move (WASD) · Aim (mouse) · THROW (Click/Space) · Dash (Shift)",
                ["hud.hint_koth"] = "Move (WASD) · Aim (mouse) · SHOVE (Click/Space) · Dash (Shift)",
                ["hud.hint_prophunt"] = "Seeker: aim + SWING (Click/Space). Hider: blend in with the props.",
                ["hud.hint_keepy"] = "Move (WASD) · Aim (mouse) · SPIKE a rival's balloon (Click/Space) · Dash (Shift)",
                ["hud.hint_glass"] = "On your turn: ↑/↓ (or W/S), or tap TOP / BOTTOM, to pick a pane.",
                ["hud.hint_chutes"] = "SPACE to roll · ← / → to pick a fork.",
                ["hud.hint_jumprope"] = "SPACE / Click to JUMP the rope.",
                ["hud.hint_simon"] = "Obey: W=head A=nose S=blink D=flip Space=jump · FREEZE = touch nothing.",
                ["hud.hint_rps"] = "Pick TWO throws, then KEEP one — tap the buttons. Out-throw your rival!",
                ["hud.hint_present"] = "Givers: tap who gets your gift. Receivers: tap a suspect to guess your giver.",

                // ── Per-game HUD status banners (DrawGameSpecific) ──
                ["hud.rl_red_freeze"] = "RED — FREEZE!",
                ["hud.rl_red"] = "RED…",
                ["hud.rl_green"] = "GREEN — GO!",
                ["hud.time"] = "Time:",
                ["hud.survive"] = "Survive:",
                ["hud.left"] = "left",
                ["hud.deep_freeze"] = "DEEP FREEZE!",
                ["hud.team_a"] = "Team A",
                ["hud.team_b"] = "Team B",
                ["hud.alive"] = "Alive:",
                ["hud.lava"] = "the floor is lava!",
                ["hud.round_lc"] = "round",
                ["hud.psych"] = "…PSYCH! keep moving",
                ["hud.group_of"] = "GROUP OF",
                ["hud.mingle_wait"] = "Mingle…",
                ["hud.row"] = "Row",
                ["hud.picks"] = "picks…",
                ["hud.swing"] = "Swing",
                ["hud.bridge"] = "bridge",
                ["hud.planks"] = "planks",
                ["hud.simon_freeze_banner"] = "FREEZE — touch nothing!",
                ["hud.simon_banner"] = "SIMON SAYS:",
                ["hud.beat"] = "Beat",
                ["hud.simon_press"] = "press W/A/S/D/Space",
                ["hud.race_top"] = "Race to the top!",
                ["hud.space_roll"] = "Space to roll",
                ["hud.lights_out"] = "Lights out…",
                ["hud.guess_giver"] = "Guess your giver!",
                ["hud.reveal"] = "Reveal",
                ["hud.disguise"] = "Disguise yourself!",
                ["hud.found"] = "Found",
                ["hud.hiding"] = "hiding",
                ["hud.dont_drop"] = "don't let it drop!",

                // ── Online / lobby ──
                ["online.title"] = "Play Online",
                ["online.subtitle"] = "Host a room or join a friend by code. Bots fill any empty slots.",
                ["online.server"] = "SERVER",
                ["online.connecting"] = "Connecting…",
                ["online.connect"] = "Connect",
                ["online.cant_reach"] = "Couldn't reach the server.",
                ["online.dev_hint"] = "Run the dev server with:  dotnet run --project server/Eliminated.Server -- 8080",
                ["online.host_room"] = "HOST A ROOM",
                ["online.difficulty"] = "Difficulty: {0}",
                ["online.create_room"] = "Create Room",
                ["online.join_by_code"] = "JOIN BY CODE",
                ["online.join"] = "Join",
                ["online.disconnect"] = "Disconnect",
                ["online.room_code"] = "ROOM CODE",
                ["online.players"] = "PLAYERS ({0})",
                ["online.bot"] = "bot",
                ["online.you"] = "you",
                ["online.add_bot"] = "Add Bot",
                ["online.start_series"] = "Start Series",
                ["online.waiting_host"] = "Waiting for the host to start…",
                ["online.leave"] = "Leave",

                // ── Game-Master captions (subtitles) ──
                ["gm.eliminated_you"] = "You were eliminated!",
                ["gm.eliminated_one"] = "{0} was eliminated.",
                ["gm.eliminated_many"] = "{0} players eliminated.",
                ["gm.red_light"] = "RED LIGHT — freeze!",
                ["gm.green_light"] = "GREEN LIGHT — go!",
                ["gm.simon_says"] = "Simon says: {0}",
                ["gm.simon_freeze"] = "Simon says: FREEZE — touch nothing!",
                ["simon.head"] = "pat your head",
                ["simon.nose"] = "touch your nose",
                ["simon.blink"] = "blink",
                ["simon.flip"] = "flip",
                ["simon.jump"] = "jump",

                // ── Controls page + account toasts ──
                ["ctrl.keyboard_p1"] = "KEYBOARD — PLAYER 1",
                ["ctrl.press_key"] = "Press a key…",
                ["ctrl.arrows_note"] = "Arrow keys always move you — they can't be unbound.",
                ["ctrl.reset"] = "Reset to defaults",
                ["ctrl.move_up"] = "Move Up",
                ["ctrl.move_down"] = "Move Down",
                ["ctrl.move_left"] = "Move Left",
                ["ctrl.move_right"] = "Move Right",
                ["ctrl.action"] = "Action / Confirm",
                ["ctrl.dash"] = "Dash",
                ["acct.saved_as"] = "Saved as {0}",
                ["acct.enter_name"] = "Enter a name first",

                // ── MenuContent flavor copy (Landing / info pages) ──
                ["menu.tagline"] = "Wholesome childhood games. Catastrophic stakes.",
                ["menu.hero_blurb"] = "Adorable little players who, frankly, signed something they didn't read. The last player standing keeps the Marbles ◍ and the bragging rights — everyone else keeps the box.",
                ["menu.footer"] = "Bring friends to betray — or fill the lobby with bots to blame.",
                ["menu.lb_title"] = "Wall of Survivors",
                ["menu.lb_subtitle"] = "Ranked by total Marbles ◍ hoarded off the backs of the fallen. The fallen are not ranked. The fallen are compost.",
                ["menu.lb_empty"] = "No champions yet. The board is as empty as the organizers' consciences. Be the first to survive!",
                ["menu.htp_title"] = "How to Play",
                ["menu.htp_subtitle"] = "…and, statistically, how to die.",
                ["menu.htp_intro"] = "Eliminated is a friendly party game for 2–8 players, in the sense that you arrive with friends and leave with fewer. The Game Master runs a mystery gauntlet of beloved childhood games, each retrofitted with a body count. Outlast everyone. Survive a game and you move on; lose one and your player is sealed into a tasteful pink-ribboned box while the crowd claps anyway.",
                ["menu.hardcore_rule"] = "Hardcore: get eliminated and your player is dead for the entire series — you spectate the rest from the comfort of the afterlife. Last player standing is crowned champion. And death means broke: the eliminated bank zero Marbles ◍, so only the survivor cashes out the run. Your one shot at a grave-side payout is the Dead Pool — wager your saved Marbles on who takes it all. No respawns, no take-backs, no HR.",
                ["menu.casual_rule"] = "Casual: eliminations only cost you the round — everyone respawns for the next game, briefly forgetting the horror. Most points across the gauntlet wins, and everyone still banks Marbles ◍ by final placement — even the early exits. The therapy bill is the same.",
                ["menu.patch_title"] = "Patch Notes",
                ["menu.patch_subtitle"] = "a running confession of everything we've changed and broken.",
                ["menu.account_title"] = "Your Player",
                ["menu.account_guest"] = "Keep your Marbles, crowns, and unlocked players across every device. Guests lose it all when the machine forgets them — like the organizers forget names.",
                ["menu.account_steam"] = "Steam remembers you. It remembers everything.",
                ["menu.controls_title"] = "Controls",
                ["menu.controls_subtitle"] = "Rebind your way to a more dignified death. The arrow keys always move you, no matter what.",
                ["menu.credits_title"] = "Credits & licenses",
                ["menu.credits_subtitle"] = "The players are ours. Almost everything else was made by people kind enough to share it.",
                ["menu.credits_audio"] = "Sound",
                ["menu.credits_art"] = "Art & models",
                ["menu.credits_music"] = "Music",
                ["menu.back_htp"] = "It's not going anywhere; neither are you.",
                ["menu.back_patch"] = "The next patch is always a nerf to you specifically.",
                ["menu.tier_last"] = "The Last Player Standing",
                ["menu.tier_seasoned"] = "Seasoned Survivor",
                ["menu.tier_mid"] = "Mid-Tier Menace",
                ["menu.tier_fodder"] = "Cannon Fodder",
                ["menu.tier_compost"] = "Barely Compost",
                ["menu.tier_fresh"] = "Fresh Meat",

                // ── Per-game guides (How to Play) ──
                ["guide.RedLight.tagline"] = "Move on green. Freeze on red. The Doll does not do warnings.",
                ["guide.RedLight.rules"] = "Reach the finish line. While the Doll watches (RED), any movement is fatal. Move only on GREEN. She does not accept appeals.",
                ["guide.RedLight.controls"] = "WASD / ↑ runs forward (or drag). A·D dodge between lanes. FREEZE the instant it turns RED.",
                ["guide.RedLight.flavor"] = "Green means go. Red means a frank conversation about your choices.",
                ["guide.Tag.tagline"] = "Blue hunts. Pink runs. Thaw your friends or shatter at the buzzer.",
                ["guide.Tag.rules"] = "🔵 BLUE freezers chase the 🩷 PINK runners — just bumping a runner freezes it (no button, contact does it). PINK free a frozen teammate the same way. At the buzzer, any PINK still frozen is out — and any BLUE who caught NOBODY goes down too.",
                ["guide.Tag.controls"] = "Move with WASD / Arrows or drag — no action button, you tag by bumping. BLUE: freeze the runners. PINK: flee, and run into a frozen teammate to THAW them.",
                ["guide.Tag.flavor"] = "Cold hands, colder severance package.",
                ["guide.Mingle.tagline"] = "Form a group of exactly the right size. Make friends or make peace with it.",
                ["guide.Mingle.rules"] = "Everyone starts on the spinning platform while the music plays. When it STOPS, a number appears — sprint into a ring circle in a group of EXACTLY that many. Too few, too many, or still on the platform? Eliminated.",
                ["guide.Mingle.controls"] = "Move with WASD / Arrows or drag. When the music stops and a number appears, pile into a ring in a group of exactly that size.",
                ["guide.Mingle.flavor"] = "Find your people. They will absolutely abandon you.",
                ["guide.GlassBridge.tagline"] = "One tile holds. One doesn't. Gamble with your feet.",
                ["guide.GlassBridge.rules"] = "One bridge, one hidden safe path. Cross ONE AT A TIME in line order: the player up front guesses LEFT or RIGHT for the next pane. Guess wrong and the glass shatters — you're gone, but everyone behind now sees the safe side.",
                ["guide.GlassBridge.controls"] = "When it's your turn, press ← / → (or A·D) to pick the LEFT or RIGHT pane.",
                ["guide.GlassBridge.flavor"] = "It's a fifty-fifty. The house already took the other fifty.",
                ["guide.TugOfWar.tagline"] = "Mash to pull. The losing team tests gravity.",
                ["guide.TugOfWar.rules"] = "Two teams. Mash the button to pull the rope your way. The team dragged over the edge is eliminated. Gravity handles the rest.",
                ["guide.TugOfWar.controls"] = "SMASH the action button (or Space / click) as fast as you can!",
                ["guide.TugOfWar.flavor"] = "Heave! Ho! Into the void with the underperformers.",
                ["guide.RpsMinusOne.tagline"] = "Throw two. Drop one. Outthink a stranger or die trying.",
                ["guide.RpsMinusOne.rules"] = "Face one opponent. Pick TWO throws before the clock runs out, then DROP one — beat the timer or you FORFEIT and you're out. Standard RPS decides it; the loser is eliminated. A tie just throws again.",
                ["guide.RpsMinusOne.controls"] = "Click two throws, then click the one to KEEP — beat the countdown or you forfeit. Tie = throw again, nobody's out.",
                ["guide.RpsMinusOne.flavor"] = "Rock, paper, scissors, minus one, plus consequences.",
                ["guide.JumpRope.tagline"] = "Skip your way across the bridge. The rope is patient. You are not.",
                ["guide.JumpRope.rules"] = "A giant rope sweeps a bridge over a long drop. Every clean JUMP carries you one plank further. Mistime it and you're swept off the edge. Reach the far side to be safe — but the rope only gets faster.",
                ["guide.JumpRope.controls"] = "Press SPACE / click / tap to JUMP the rope and cross the bridge.",
                ["guide.JumpRope.flavor"] = "It's not the rope that kills you. It's the plank you never reach.",
                ["guide.Boomerang.tagline"] = "Throw, dodge, grab questionable powerups. Last player standing.",
                ["guide.Boomerang.rules"] = "A free-for-all arena. Hurl your boomerang, dodge incoming, and grab wild powerups (roughly half want you dead). Last player standing survives.",
                ["guide.Boomerang.controls"] = "Move with WASD / Arrows. Aim with the mouse, click to THROW. Dash with Shift.",
                ["guide.Boomerang.flavor"] = "All fun and games until it returns to sender.",
                ["guide.Dodgeball.tagline"] = "Two teams, one line, a tasteful hail of rubber. Last team standing.",
                ["guide.Dodgeball.rules"] = "Grab a ball and hurl it across the line. Anyone hit (no shield) is OUT. Dash to dodge. Wipe out the other team — or just have more players left when the buzzer sounds.",
                ["guide.Dodgeball.controls"] = "WASD move · mouse aim · click / SPACE throw · SHIFT dash to dodge.",
                ["guide.Dodgeball.flavor"] = "Dodge, duck, dip, dive, and die.",
                ["guide.MusicalChairs.tagline"] = "When the music stops, grab a seat. Or grab a clue.",
                ["guide.MusicalChairs.rules"] = "Roam while the music plays. The instant it STOPS, race to a chair. One player per chair — anyone left standing is ELIMINATED. A chair vanishes each round, because scarcity is the point.",
                ["guide.MusicalChairs.controls"] = "Move with WASD / Arrows or drag. Chairs only appear when the music STOPS — then sprint!",
                ["guide.MusicalChairs.flavor"] = "The music is lying to you. It always stops. Like everything.",
                ["guide.PresentSwap.tagline"] = "Pick a mark in the dark. Guess your giver, or pay for the gesture.",
                ["guide.PresentSwap.rules"] = "When the lights drop, secret GIVERS each slip a gift to a player of their choosing. Lights up: if you got a gift, guess who gave it — guess right and the giver is OUT; guess wrong and YOU'RE out. Givers: choose your mark, then stay hidden.",
                ["guide.PresentSwap.controls"] = "Secret giver? Tap a player to gift while the lights are out. Got a gift? Tap whoever you think slipped it to you.",
                ["guide.PresentSwap.flavor"] = "Someone left you a present. How thoughtful. How incriminating.",
                ["guide.PropHunt.tagline"] = "Become the furniture. One player has a sword and a quota.",
                ["guide.PropHunt.rules"] = "Everyone disguises as a random prop and blends into a room of identical decoys. ONE Seeker stalks with a blade — but only a few swings before it dulls. Get skewered and you're boxed; hold perfectly still and you're just a barrel.",
                ["guide.PropHunt.controls"] = "Hiders: WASD / Arrows to creep — but HOLD STILL to blend in. Seeker: move + SPACE / click to slash the nearest object.",
                ["guide.PropHunt.flavor"] = "If you can't beat the décor, become the décor.",
                ["guide.ChutesAndLadders.tagline"] = "Climb the ladders. Gamble the chutes. Beat the clock.",
                ["guide.ChutesAndLadders.rules"] = "RACE to the top (square 64) for SAFETY. Ladders launch you up. Land on a CHUTE and you must GAMBLE LEFT or RIGHT: one side resets you to START, the other drops you into the ABYSS — eliminated. A chute's sides never change, so watch who falls first.",
                ["guide.ChutesAndLadders.controls"] = "SMASH to ROLL (or SPACE). 🪜 climb · at a CHUTE pick ◀ LEFT / RIGHT ▶ (A·D or ←·→). Reach 🏁 before the clock!",
                ["guide.ChutesAndLadders.flavor"] = "The ladders giveth. The chutes ask you to pick your own doom. The clock just laughs.",
                ["guide.SimonSays.tagline"] = "Do exactly as you're told. Fumble, freeze up, or twitch — and you're done.",
                ["guide.SimonSays.rules"] = "The Game Master barks an order — do the matching move before the timer runs out. 🙌 head · 👃 nose · 👀 blink · 🤸 flip · ⬆️ jump. On 🧊 FREEZE, touch NOTHING. Wrong move, too slow, or one nervous twitch: eliminated.",
                ["guide.SimonSays.controls"] = "W pat head · A touch nose · S blink · D flip · SPACE jump — and FREEZE means hands OFF. (Follows your rebinds.)",
                ["guide.SimonSays.flavor"] = "Simon says obey. Simon does not say there's a refund.",
                ["guide.KeepyUppy.tagline"] = "Keep your balloon off the floor. Pop everyone else's. Teamwork!™",
                ["guide.KeepyUppy.rules"] = "You get one balloon in your colors. Don't let it touch the floor and don't let it get popped — either one and you're done. Bump it to bat it up; SPIKE to burst a rival's. The air keeps getting heavier.",
                ["guide.KeepyUppy.controls"] = "WASD / Arrows or drag to move under your balloon (you auto-bat it up). SPACE / click to pop a rival's.",
                ["guide.KeepyUppy.flavor"] = "It's a children's party game. The children are gone. The pins remain.",
                ["guide.KingOfTheHill.tagline"] = "The floor is lava. The islands are sinking. The crown is petty.",
                ["guide.KingOfTheHill.rules"] = "The floor is lava and the islands sink one by one. Hop between them to stay off the floor, grab powerups, and shove rivals into the magma. Islands run out — last player not-on-fire is CHAMPION.",
                ["guide.KingOfTheHill.controls"] = "WASD / Arrows or drag to hop between sinking islands. Aim with the mouse, then CLICK / SPACE to SHOVE a rival into the lava.",
                ["guide.KingOfTheHill.flavor"] = "All thrones are temporary. These ones are also sinking.",

                // ── Info pages: Account / How-to-Play / Players shop ──
                ["acct.col_player"] = "PLAYER",
                ["acct.col_title"] = "TITLE",
                ["acct.col_crowns"] = "CROWNS",
                ["acct.steam_submit"] = "Your marbles are submitted to the Steam leaderboards at the end of every series.",
                ["acct.steam_global"] = "Global rankings live on Steam — launch through Steam and your hoard joins the Wall.",
                ["acct.everything"] = "Everything you've earned, and everyone you've outlived.",
                ["acct.signed_in_steam"] = "Signed in via Steam",
                ["acct.display_name"] = "DISPLAY NAME",
                ["acct.guest"] = "Playing as a guest player.",
                ["acct.stat_marbles"] = "◍ MARBLES",
                ["acct.stat_crowns"] = "👑 CROWNS",
                ["acct.stat_rounds"] = "🩸 ROUNDS",
                ["acct.stat_title"] = "🏷 TITLE",
                ["acct.steam_cloud"] = "Your hoard, crowns, and unlocked players sync through Steam Cloud. Nothing is forgotten.",
                ["htp.the_games"] = "THE GAMES",
                ["htp.controls"] = "Controls",
                ["htp.controls_caps"] = "CONTROLS",
                ["htp.live_bots"] = "LIVE • bots",
                ["shop.choose_player"] = "Choose your Player",
                ["shop.player_hint"] = "Tap to wear. Locked players cost Marbles ◍ — earned the honest way, by outliving your friends.",
                ["shop.wearing"] = "PLAYING AS:",
                ["shop.tab_players"] = "Players",
                ["shop.tab_acc"] = "Accessories",
                ["shop.cant_draw"] = "Couldn't draw the wardrobe:",
                ["shop.selected"] = "SELECTED",
                ["shop.tap_wear"] = "Tap to wear",
                ["shop.worn_remove"] = "WORN — tap to remove",
                ["shop.slot_hats"] = "🎩  HATS",
                ["shop.slot_eyewear"] = "👓  EYEWEAR",
                ["shop.slot_neck"] = "🧣  NECKWEAR",
                ["shop.slot_ear"] = "🌼  BEHIND THE EAR",
            },
            ["es"] = new Dictionary<string, string>
            {
                ["ui.title"] = "ELIMINADO",
                ["ui.tagline"] = "Un alegre juego de fiesta donde todos mueren.",
                ["ui.play_solo_casual"] = "En solitario vs Bots — Casual",
                ["ui.play_solo_hardcore"] = "En solitario vs Bots — Difícil (el último jugador en pie)",
                ["ui.local_coop"] = "Cooperativo local",
                ["ui.settings"] = "Ajustes",
                ["ui.quit"] = "Salir",
                ["ui.back_to_menu"] = "Volver al menú",
                ["ui.save_and_back"] = "Guardar y volver",
                ["ui.get_ready"] = "Prepárate…",
                ["ui.reckoning"] = "El Ajuste de Cuentas",
                ["ui.series_over"] = "Se Ha Decidido un Ganador",
                ["ui.marbles"] = "Canicas",
                ["ui.round"] = "Ronda {0}",
                ["gm.game_intro"] = "Maestro del Juego: Juego {0} — {1}.",
                ["gm.room_intro"] = "Escenario: {0}.",
                ["room.courtyard"] = "El Patio",
                ["room.neon"] = "Distrito Neón",
                ["room.candy"] = "Reino de Caramelo",
                ["room.toxic"] = "La Planta Tóxica",
                ["room.beach"] = "Costa Soleada",
                ["room.haunt"] = "La Mansión Encantada",
                ["gm.champion"] = "Maestro del Juego: ¡{0} es el último jugador en pie!",
                ["game.RedLight"] = "Luz roja, luz verde",
                ["game.Tag"] = "Pilla-pilla congelado",
                ["game.Mingle"] = "Mézclate",
                ["game.GlassBridge"] = "Puente de cristal",
                ["game.TugOfWar"] = "Tira y afloja",
                ["game.RpsMinusOne"] = "Piedra, papel o tijera menos uno",
                ["game.JumpRope"] = "Comba asesina",
                ["game.Boomerang"] = "Pelea de bumeranes",
                ["game.Dodgeball"] = "Balón prisionero",
                ["game.MusicalChairs"] = "Sillas musicales",
                ["game.PresentSwap"] = "Sabotaje de Amigo Invisible",
                ["game.PropHunt"] = "Caza de objetos",
                ["game.ChutesAndLadders"] = "Serpientes y escaleras",
                ["game.SimonSays"] = "Simón dice",
                ["game.KeepyUppy"] = "Mantén el globo",
                ["game.KingOfTheHill"] = "Rey de las islas de lava",

                // ── UI chrome / navigation ──
                ["ui.back"] = "← Atrás",
                ["ui.play"] = "JUGAR",
                ["ui.your_player"] = "Tu jugador",
                ["ui.choose_how"] = "ELIGE CÓMO JUGAR",
                ["ui.play_online"] = "Jugar en línea",
                ["ui.solo_vs_bots"] = "En solitario vs Bots",
                ["ui.local_coop_n"] = "Cooperativo local — {0} jugadores",
                ["ui.coop_needs_gamepad"] = "* El cooperativo local necesita un mando conectado",
                ["ui.choose_difficulty"] = "{0}  ·  ELIGE DIFICULTAD",
                ["ui.casual"] = "Casual",
                ["ui.hardcore"] = "Difícil",
                ["ui.save"] = "Guardar",
                ["ui.saved"] = "Guardado",
                ["nav.leaderboard"] = "Clasificación",
                ["nav.how_to_play"] = "Cómo jugar",
                ["nav.patch_notes"] = "Notas del parche",

                // ── Settings ──
                ["set.language"] = "Idioma:",
                ["set.colorblind"] = "Modo daltónico:",
                ["set.subtitles"] = "Leyendas / subtítulos",
                ["set.reduce_motion"] = "Reducir destellos y vibración",
                ["set.master_volume"] = "Volumen general: {0}%",
                ["set.game_volume"] = "Sonido del juego: {0}%",
                ["set.music_volume"] = "Música de fondo: {0}%",
                ["set.music"] = "Música",
                ["set.remap"] = "Reasignar controles",
                ["set.credits"] = "Créditos y licencias",
                ["cb.Normal"] = "Desactivado",
                ["cb.RedGreen"] = "Rojo–Verde",
                ["cb.BlueYellow"] = "Azul–Amarillo",

                // ── Results / HUD ──
                ["res.safe"] = "A SALVO",
                ["res.out"] = "FUERA",
                ["res.you"] = "(TÚ)",
                ["hud.countdown"] = "3 · 2 · 1 · ¡YA!",
                ["hud.round_game"] = "Ronda {0} · {1}",
                ["hud.players_alive"] = "Jugadores vivos: {0}",
                ["hud.hint_default"] = "WASD/Flechas para moverte.",
                ["hud.hint_redlight"] = "Muévete en VERDE (WASD/Flechas). ¡QUIETO en ROJO!",
                ["hud.hint_tug"] = "¡APORREA Espacio / Clic para arrastrar a tu equipo a la victoria!",
                ["hud.hint_boomerang"] = "Mover (WASD) · Apuntar (ratón) · Lanzar (Clic/Espacio) · Esquivar (Shift)",
                ["hud.hint_move_action"] = "WASD/Flechas mover · Espacio acción · Shift esquivar",
                ["hud.hint_glass"] = "En tu turno: ↑/↓ (o W/S), o toca ARRIBA / ABAJO, para elegir baldosa.",
                ["hud.hint_chutes"] = "ESPACIO para tirar · ← / → para elegir bifurcación.",
                ["hud.hint_jumprope"] = "ESPACIO / Clic para SALTAR la comba.",
                ["hud.hint_simon"] = "Obedece: W=cabeza A=nariz S=parpadeo D=voltereta Espacio=salto · QUIETO = no toques nada.",
                ["hud.hint_rps"] = "Duelo de piedra-papel-tijera (asistido por bots en esta versión).",
                ["hud.hint_present"] = "Amigo invisible — adivinar está asistido por bots en esta versión.",

                // ── Per-game HUD status banners (DrawGameSpecific) ──
                ["hud.rl_red_freeze"] = "ROJO — ¡QUIETO!",
                ["hud.rl_red"] = "ROJO…",
                ["hud.rl_green"] = "VERDE — ¡YA!",
                ["hud.time"] = "Tiempo:",
                ["hud.survive"] = "Sobrevive:",
                ["hud.left"] = "restantes",
                ["hud.deep_freeze"] = "¡CONGELACIÓN PROFUNDA!",
                ["hud.team_a"] = "Equipo A",
                ["hud.team_b"] = "Equipo B",
                ["hud.alive"] = "Vivos:",
                ["hud.lava"] = "¡el suelo es lava!",
                ["hud.round_lc"] = "ronda",
                ["hud.psych"] = "…¡PSIQUE! sigue moviéndote",
                ["hud.group_of"] = "¡GRUPO DE",
                ["hud.mingle_wait"] = "Mézclate…",
                ["hud.row"] = "Fila",
                ["hud.picks"] = "elige…",
                ["hud.swing"] = "Vuelta",
                ["hud.bridge"] = "puente",
                ["hud.planks"] = "tablones",
                ["hud.simon_freeze_banner"] = "QUIETO — ¡no toques nada!",
                ["hud.simon_banner"] = "SIMÓN DICE:",
                ["hud.beat"] = "Compás",
                ["hud.simon_press"] = "pulsa W/A/S/D/Espacio",
                ["hud.race_top"] = "¡Corre a la cima!",
                ["hud.space_roll"] = "Espacio para tirar",
                ["hud.lights_out"] = "Luces apagadas…",
                ["hud.guess_giver"] = "¡Adivina quién te regaló!",
                ["hud.reveal"] = "Revelación",
                ["hud.disguise"] = "¡Disfrázate!",
                ["hud.found"] = "Encontrados",
                ["hud.hiding"] = "escondidos",
                ["hud.dont_drop"] = "¡no dejes que caiga!",

                // ── Online / lobby ──
                ["online.title"] = "Jugar en línea",
                ["online.subtitle"] = "Crea una sala o únete a un amigo con un código. Los bots llenan los huecos.",
                ["online.server"] = "SERVIDOR",
                ["online.connecting"] = "Conectando…",
                ["online.connect"] = "Conectar",
                ["online.cant_reach"] = "No se pudo contactar con el servidor.",
                ["online.dev_hint"] = "Inicia el servidor de pruebas con:  dotnet run --project server/Eliminated.Server -- 8080",
                ["online.host_room"] = "CREAR UNA SALA",
                ["online.difficulty"] = "Dificultad: {0}",
                ["online.create_room"] = "Crear sala",
                ["online.join_by_code"] = "UNIRSE POR CÓDIGO",
                ["online.join"] = "Unirse",
                ["online.disconnect"] = "Desconectar",
                ["online.room_code"] = "CÓDIGO DE SALA",
                ["online.players"] = "JUGADORES ({0})",
                ["online.bot"] = "bot",
                ["online.you"] = "tú",
                ["online.add_bot"] = "Añadir bot",
                ["online.start_series"] = "Empezar serie",
                ["online.waiting_host"] = "Esperando a que el anfitrión empiece…",
                ["online.leave"] = "Salir",

                // ── Game-Master captions (subtitles) ──
                ["gm.eliminated_you"] = "¡Has sido eliminado!",
                ["gm.eliminated_one"] = "{0} ha sido eliminado.",
                ["gm.eliminated_many"] = "{0} jugadores eliminados.",
                ["gm.red_light"] = "LUZ ROJA — ¡quieto!",
                ["gm.green_light"] = "LUZ VERDE — ¡corre!",
                ["gm.simon_says"] = "Simón dice: {0}",
                ["gm.simon_freeze"] = "Simón dice: ¡QUIETO — no toques nada!",
                ["simon.head"] = "tócate la cabeza",
                ["simon.nose"] = "tócate la nariz",
                ["simon.blink"] = "parpadea",
                ["simon.flip"] = "da una voltereta",
                ["simon.jump"] = "salta",

                // ── Controls page + account toasts ──
                ["ctrl.keyboard_p1"] = "TECLADO — JUGADOR 1",
                ["ctrl.press_key"] = "Pulsa una tecla…",
                ["ctrl.arrows_note"] = "Las flechas siempre te mueven — no se pueden reasignar.",
                ["ctrl.reset"] = "Restablecer valores",
                ["ctrl.move_up"] = "Mover arriba",
                ["ctrl.move_down"] = "Mover abajo",
                ["ctrl.move_left"] = "Mover izquierda",
                ["ctrl.move_right"] = "Mover derecha",
                ["ctrl.action"] = "Acción / Confirmar",
                ["ctrl.dash"] = "Esquivar",
                ["acct.saved_as"] = "Guardado como {0}",
                ["acct.enter_name"] = "Escribe un nombre primero",

                // ── MenuContent flavor copy (Landing / info pages) ──
                ["menu.tagline"] = "Juegos infantiles sanos. Apuestas catastróficas.",
                ["menu.hero_blurb"] = "Adorables jugadores que, francamente, firmaron algo que no leyeron. El último jugador en pie se queda con las Canicas ◍ y el derecho a fanfarronear; los demás se quedan con la caja.",
                ["menu.footer"] = "Trae amigos a los que traicionar, o llena la sala de bots a los que culpar.",
                ["menu.lb_title"] = "Muro de Supervivientes",
                ["menu.lb_subtitle"] = "Clasificados por el total de Canicas ◍ acumuladas a costa de los caídos. Los caídos no se clasifican. Los caídos son abono.",
                ["menu.lb_empty"] = "Aún no hay campeones. El tablero está tan vacío como la conciencia de los organizadores. ¡Sé el primero en sobrevivir!",
                ["menu.htp_title"] = "Cómo jugar",
                ["menu.htp_subtitle"] = "…y, estadísticamente, cómo morir.",
                ["menu.htp_intro"] = "Eliminado es un alegre juego de fiesta para 2–8 jugadores, en el sentido de que llegas con amigos y te vas con menos. El Maestro del Juego dirige una serie misteriosa de queridos juegos infantiles, cada uno con su recuento de víctimas. Sobrevive a todos. Supera un juego y avanzas; pierde uno y tu jugador queda sellado en una elegante caja con lazo rosa mientras el público aplaude igualmente.",
                ["menu.hardcore_rule"] = "Difícil: si te eliminan, tu jugador muere durante toda la serie; ves el resto desde la comodidad del más allá. El último jugador en pie es coronado campeón. Y morir es quedarse sin nada: los eliminados se llevan cero Canicas ◍, así que solo el superviviente cobra la partida. Tu única opción de cobrar desde la tumba es la Quiniela de los Muertos: apuesta tus Canicas guardadas a quién gana. Sin reapariciones, sin repeticiones, sin Recursos Humanos.",
                ["menu.casual_rule"] = "Casual: las eliminaciones solo te cuestan la ronda; todos reaparecen para el siguiente juego, olvidando brevemente el horror. Gana quien más puntos consiga en la serie, y todos se llevan Canicas ◍ según su puesto final, incluso quienes caen pronto. La factura de la terapia es la misma.",
                ["menu.patch_title"] = "Notas del parche",
                ["menu.patch_subtitle"] = "una confesión continua de todo lo que hemos cambiado y roto.",
                ["menu.account_title"] = "Tu jugador",
                ["menu.account_guest"] = "Conserva tus Canicas, coronas y jugadores desbloqueados en cualquier dispositivo. Los invitados lo pierden todo cuando la máquina los olvida, igual que los organizadores olvidan los nombres.",
                ["menu.account_steam"] = "Steam te recuerda. Lo recuerda todo.",
                ["menu.controls_title"] = "Controles",
                ["menu.controls_subtitle"] = "Reasigna las teclas hacia una muerte más digna. Las flechas siempre te mueven, pase lo que pase.",
                ["menu.credits_title"] = "Créditos y licencias",
                ["menu.credits_subtitle"] = "Los jugadores son nuestros. Casi todo lo demás lo hicieron personas lo bastante amables como para compartirlo.",
                ["menu.credits_audio"] = "Sonido",
                ["menu.credits_art"] = "Arte y modelos",
                ["menu.credits_music"] = "Música",
                ["menu.back_htp"] = "No se va a ninguna parte; tú tampoco.",
                ["menu.back_patch"] = "El próximo parche siempre es un nerf dirigido a ti en concreto.",
                ["menu.tier_last"] = "El Último Jugador en Pie",
                ["menu.tier_seasoned"] = "Superviviente Veterano",
                ["menu.tier_mid"] = "Amenaza de Medio Pelo",
                ["menu.tier_fodder"] = "Carne de Cañón",
                ["menu.tier_compost"] = "Apenas Abono",
                ["menu.tier_fresh"] = "Carne Fresca",

                // ── Per-game guides (How to Play) ──
                ["guide.RedLight.tagline"] = "Avanza en verde. Quieto en rojo. La Muñeca no avisa.",
                ["guide.RedLight.rules"] = "Llega a la meta. Mientras la Muñeca mira (ROJO), cualquier movimiento es fatal. Muévete solo en VERDE. No acepta apelaciones.",
                ["guide.RedLight.controls"] = "WASD / ↑ avanza (o arrastra). A·D esquiva entre carriles. ¡QUÉDATE QUIETO en cuanto se ponga ROJO!",
                ["guide.RedLight.flavor"] = "Verde significa adelante. Rojo significa una charla franca sobre tus decisiones.",
                ["guide.Tag.tagline"] = "El azul caza. El rosa huye. Descongela a tus amigos o hazte añicos al sonar la bocina.",
                ["guide.Tag.rules"] = "🔵 Los congeladores AZULES persiguen a los corredores 🩷 ROSAS: basta con chocar a un corredor para congelarlo (sin botón, lo hace el contacto). Los ROSAS liberan a un compañero congelado igual. Al sonar la bocina, todo ROSA que siga congelado queda fuera, y todo AZUL que no atrapó a NADIE también cae.",
                ["guide.Tag.controls"] = "Muévete con WASD / Flechas o arrastra: sin botón de acción, atrapas al chocar. AZUL: congela a los corredores. ROSA: huye y choca con un compañero congelado para DESCONGELARLO.",
                ["guide.Tag.flavor"] = "Manos frías, finiquito más frío.",
                ["guide.Mingle.tagline"] = "Forma un grupo del tamaño exacto. Haz amigos o hazte a la idea.",
                ["guide.Mingle.rules"] = "Todos empiezan en la plataforma giratoria mientras suena la música. Cuando PARA, aparece un número: corre a un círculo en un grupo de EXACTAMENTE esa cantidad. ¿Muy pocos, demasiados o aún en la plataforma? Eliminado.",
                ["guide.Mingle.controls"] = "Muévete con WASD / Flechas o arrastra. Cuando la música pare y aparezca un número, métete en un círculo en un grupo de ese tamaño exacto.",
                ["guide.Mingle.flavor"] = "Encuentra a tu gente. Te abandonarán sin dudarlo.",
                ["guide.GlassBridge.tagline"] = "Una baldosa aguanta. Otra no. Apuesta con los pies.",
                ["guide.GlassBridge.rules"] = "Un puente, un camino seguro oculto. Cruza DE UNO EN UNO por orden de fila: el jugador de delante adivina IZQUIERDA o DERECHA para el siguiente panel. Si fallas, el cristal se rompe: estás fuera, pero todos los de atrás ya ven el lado seguro.",
                ["guide.GlassBridge.controls"] = "Cuando sea tu turno, pulsa ← / → (o A·D) para elegir el panel IZQUIERDO o DERECHO.",
                ["guide.GlassBridge.flavor"] = "Es un cincuenta-cincuenta. La casa ya se quedó con el otro cincuenta.",
                ["guide.TugOfWar.tagline"] = "Aporrea para tirar. El equipo perdedor pone a prueba la gravedad.",
                ["guide.TugOfWar.rules"] = "Dos equipos. Aporrea el botón para tirar de la cuerda hacia tu lado. El equipo arrastrado por el borde queda eliminado. La gravedad hace el resto.",
                ["guide.TugOfWar.controls"] = "¡APORREA el botón de acción (o Espacio / clic) lo más rápido que puedas!",
                ["guide.TugOfWar.flavor"] = "¡Tira! ¡Más fuerte! Al vacío con los que rinden poco.",
                ["guide.RpsMinusOne.tagline"] = "Lanza dos. Descarta una. Supera en astucia a un desconocido o muere en el intento.",
                ["guide.RpsMinusOne.rules"] = "Te enfrentas a un rival. Elige DOS jugadas antes de que se acabe el tiempo y luego DESCARTA una: vence al reloj o PIERDES por incomparecencia y quedas fuera. El piedra-papel-tijera normal decide; el perdedor es eliminado. Un empate vuelve a empezar.",
                ["guide.RpsMinusOne.controls"] = "Haz clic en dos jugadas y luego en la que QUIERES quedarte: vence la cuenta atrás o pierdes. Empate = se repite, nadie sale.",
                ["guide.RpsMinusOne.flavor"] = "Piedra, papel, tijera, menos uno, más consecuencias.",
                ["guide.JumpRope.tagline"] = "Salta a la comba para cruzar el puente. La cuerda es paciente. Tú no.",
                ["guide.JumpRope.rules"] = "Una cuerda gigante barre un puente sobre una gran caída. Cada SALTO limpio te lleva un tablón más lejos. Si calculas mal, te barre por el borde. Llega al otro lado para estar a salvo, pero la cuerda solo va más rápido.",
                ["guide.JumpRope.controls"] = "Pulsa ESPACIO / clic / toca para SALTAR la comba y cruzar el puente.",
                ["guide.JumpRope.flavor"] = "No es la cuerda lo que te mata. Es el tablón al que nunca llegas.",
                ["guide.Boomerang.tagline"] = "Lanza, esquiva, agarra potenciadores dudosos. Último jugador en pie.",
                ["guide.Boomerang.rules"] = "Una arena de todos contra todos. Lanza tu bumerán, esquiva los que vienen y agarra potenciadores salvajes (más o menos la mitad te quieren muerto). Sobrevive el último jugador en pie.",
                ["guide.Boomerang.controls"] = "Muévete con WASD / Flechas. Apunta con el ratón, haz clic para LANZAR. Esquiva con Shift.",
                ["guide.Boomerang.flavor"] = "Todo diversión hasta que vuelve a su remitente.",
                ["guide.Dodgeball.tagline"] = "Dos equipos, una línea, una elegante lluvia de goma. Último equipo en pie.",
                ["guide.Dodgeball.rules"] = "Agarra una pelota y lánzala al otro lado de la línea. Quien reciba un impacto (sin escudo) queda FUERA. Esquiva con el dash. Aniquila al otro equipo, o simplemente ten más jugadores cuando suene la bocina.",
                ["guide.Dodgeball.controls"] = "WASD mover · ratón apuntar · clic / ESPACIO lanzar · SHIFT dash para esquivar.",
                ["guide.Dodgeball.flavor"] = "Esquiva, agáchate, finta, lánzate y muere.",
                ["guide.MusicalChairs.tagline"] = "Cuando pare la música, pilla una silla. O pilla una pista.",
                ["guide.MusicalChairs.rules"] = "Pasea mientras suena la música. En cuanto PARA, corre a una silla. Un jugador por silla: quien se quede de pie queda ELIMINADO. Cada ronda desaparece una silla, porque la escasez es lo importante.",
                ["guide.MusicalChairs.controls"] = "Muévete con WASD / Flechas o arrastra. Las sillas solo aparecen cuando la música PARA: ¡entonces corre!",
                ["guide.MusicalChairs.flavor"] = "La música te miente. Siempre para. Como todo.",
                ["guide.PresentSwap.tagline"] = "Elige a una víctima en la oscuridad. Adivina quién te regaló, o paga por el gesto.",
                ["guide.PresentSwap.rules"] = "Cuando se apagan las luces, GENEROSOS secretos entregan un regalo al jugador que elijan. Luces encendidas: si recibiste un regalo, adivina quién lo dio; aciertas y el generoso queda FUERA; fallas y SALES tú. Generosos: elegid a vuestra víctima y permaneced ocultos.",
                ["guide.PresentSwap.controls"] = "¿Generoso secreto? Toca a un jugador para regalarle mientras están las luces apagadas. ¿Recibiste un regalo? Toca a quien creas que te lo dejó.",
                ["guide.PresentSwap.flavor"] = "Alguien te dejó un regalo. Qué detalle. Qué incriminatorio.",
                ["guide.PropHunt.tagline"] = "Conviértete en el mobiliario. Un jugador tiene una espada y una cuota.",
                ["guide.PropHunt.rules"] = "Todos se disfrazan de un objeto aleatorio y se mezclan en una sala de señuelos idénticos. UN Buscador acecha con una hoja, pero con solo unos golpes antes de que se desafile. Si te ensartan, a la caja; quédate totalmente quieto y serás solo un barril.",
                ["guide.PropHunt.controls"] = "Escondidos: WASD / Flechas para moveros sigilosos, pero QUEDAOS QUIETOS para mezclaros. Buscador: muévete + ESPACIO / clic para cortar el objeto más cercano.",
                ["guide.PropHunt.flavor"] = "Si no puedes con la decoración, hazte decoración.",
                ["guide.ChutesAndLadders.tagline"] = "Sube por las escaleras. Apuesta en los toboganes. Vence al reloj.",
                ["guide.ChutesAndLadders.rules"] = "CORRE a la cima (casilla 64) para estar a SALVO. Las escaleras te impulsan hacia arriba. Si caes en un TOBOGÁN, debes APOSTAR IZQUIERDA o DERECHA: un lado te devuelve a la SALIDA, el otro te lanza al ABISMO (eliminado). Los lados de un tobogán nunca cambian, así que observa quién cae primero.",
                ["guide.ChutesAndLadders.controls"] = "APORREA para TIRAR (o ESPACIO). 🪜 sube · en un TOBOGÁN elige ◀ IZQUIERDA / DERECHA ▶ (A·D o ←·→). ¡Llega a 🏁 antes del reloj!",
                ["guide.ChutesAndLadders.flavor"] = "Las escaleras dan. Los toboganes te piden elegir tu propia perdición. El reloj solo se ríe.",
                ["guide.SimonSays.tagline"] = "Haz exactamente lo que se te ordena. Si fallas, te bloqueas o te mueves, estás acabado.",
                ["guide.SimonSays.rules"] = "El Maestro del Juego da una orden: haz el movimiento correcto antes de que acabe el tiempo. 🙌 cabeza · 👃 nariz · 👀 parpadear · 🤸 voltereta · ⬆️ saltar. En 🧊 QUIETO, no toques NADA. Movimiento erróneo, demasiado lento o un solo tic nervioso: eliminado.",
                ["guide.SimonSays.controls"] = "W cabeza · A nariz · S parpadear · D voltereta · ESPACIO saltar; y QUIETO significa manos QUIETAS. (Sigue tus reasignaciones.)",
                ["guide.SimonSays.flavor"] = "Simón dice que obedezcas. Simón no dice que haya reembolso.",
                ["guide.KeepyUppy.tagline"] = "Mantén tu globo lejos del suelo. Revienta el de los demás. ¡Trabajo en equipo!™",
                ["guide.KeepyUppy.rules"] = "Tienes un globo con tus colores. No dejes que toque el suelo ni que lo revienten: cualquiera de las dos y estás acabado. Dale toques para mantenerlo arriba; CLAVA para reventar el de un rival. El aire se vuelve cada vez más pesado.",
                ["guide.KeepyUppy.controls"] = "WASD / Flechas o arrastra para colocarte bajo tu globo (lo golpeas automáticamente). ESPACIO / clic para reventar el de un rival.",
                ["guide.KeepyUppy.flavor"] = "Es un juego de fiesta infantil. Los niños se fueron. Los alfileres quedan.",
                ["guide.KingOfTheHill.tagline"] = "El suelo es lava. Las islas se hunden. La corona es mezquina.",
                ["guide.KingOfTheHill.rules"] = "El suelo es lava y las islas se hunden una a una. Salta entre ellas para no tocar el suelo, agarra potenciadores y empuja a los rivales al magma. Las islas se acaban: el último jugador sin arder es CAMPEÓN.",
                ["guide.KingOfTheHill.controls"] = "WASD / Flechas o arrastra para saltar entre islas que se hunden. Apunta con el ratón y luego CLIC / ESPACIO para EMPUJAR a un rival a la lava.",
                ["guide.KingOfTheHill.flavor"] = "Todos los tronos son temporales. Estos además se hunden.",

                // ── Info pages: Account / How-to-Play / Players shop ──
                ["acct.col_player"] = "JUGADOR",
                ["acct.col_title"] = "TÍTULO",
                ["acct.col_crowns"] = "CORONAS",
                ["acct.steam_submit"] = "Tus canicas se envían a las clasificaciones de Steam al final de cada serie.",
                ["acct.steam_global"] = "Las clasificaciones globales están en Steam: inicia desde Steam y tu botín se une al Muro.",
                ["acct.everything"] = "Todo lo que has ganado, y todos a quienes has sobrevivido.",
                ["acct.signed_in_steam"] = "Conectado mediante Steam",
                ["acct.display_name"] = "NOMBRE VISIBLE",
                ["acct.guest"] = "Jugando como jugador invitado.",
                ["acct.stat_marbles"] = "◍ CANICAS",
                ["acct.stat_crowns"] = "👑 CORONAS",
                ["acct.stat_rounds"] = "🩸 RONDAS",
                ["acct.stat_title"] = "🏷 TÍTULO",
                ["acct.steam_cloud"] = "Tu botín, coronas y jugadores desbloqueados se sincronizan con Steam Cloud. Nada se olvida.",
                ["htp.the_games"] = "LOS JUEGOS",
                ["htp.controls"] = "Controles",
                ["htp.controls_caps"] = "CONTROLES",
                ["htp.live_bots"] = "EN VIVO • bots",
                ["shop.choose_player"] = "Elige tu jugador",
                ["shop.player_hint"] = "Toca para ponértelo. Los jugadores bloqueados cuestan Canicas ◍, ganadas de forma honesta sobreviviendo a tus amigos.",
                ["shop.wearing"] = "JUEGAS COMO:",
                ["shop.tab_players"] = "Jugadores",
                ["shop.tab_acc"] = "Accesorios",
                ["shop.cant_draw"] = "No se pudo dibujar el vestuario:",
                ["shop.selected"] = "SELECCIONADO",
                ["shop.tap_wear"] = "Toca para ponértelo",
                ["shop.worn_remove"] = "PUESTO — toca para quitar",
                ["shop.slot_hats"] = "🎩  SOMBREROS",
                ["shop.slot_eyewear"] = "👓  GAFAS",
                ["shop.slot_neck"] = "🧣  CUELLO",
                ["shop.slot_ear"] = "🌼  DETRÁS DE LA OREJA",
            },
            ["fr"] = new Dictionary<string, string>
            {
                ["ui.title"] = "ÉLIMINÉ",
                ["ui.tagline"] = "Un gentil jeu de fête où tout le monde meurt.",
                ["ui.play_solo_casual"] = "Solo contre des bots — Décontracté",
                ["ui.play_solo_hardcore"] = "Solo contre des bots — Difficile (dernier joueur debout)",
                ["ui.local_coop"] = "Coop local",
                ["ui.settings"] = "Paramètres",
                ["ui.quit"] = "Quitter",
                ["ui.back_to_menu"] = "Retour au menu",
                ["ui.save_and_back"] = "Enregistrer et revenir",
                ["ui.get_ready"] = "Préparez-vous…",
                ["ui.reckoning"] = "Le Verdict",
                ["ui.series_over"] = "Un Gagnant a été Désigné",
                ["ui.marbles"] = "Billes",
                ["ui.round"] = "Manche {0}",
                ["gm.game_intro"] = "Maître du Jeu : Jeu {0} — {1}.",
                ["gm.room_intro"] = "L'arène : {0}.",
                ["room.courtyard"] = "La Cour",
                ["room.neon"] = "Quartier Néon",
                ["room.candy"] = "Royaume des Bonbons",
                ["room.toxic"] = "L'Usine Toxique",
                ["room.beach"] = "Côte Ensoleillée",
                ["room.haunt"] = "Le Manoir Hanté",
                ["gm.champion"] = "Maître du Jeu : {0} est le dernier joueur debout !",
                ["game.RedLight"] = "Un, deux, trois, soleil",
                ["game.Tag"] = "Jeu du gel",
                ["game.Mingle"] = "Mêlez-vous",
                ["game.GlassBridge"] = "Pont de verre",
                ["game.TugOfWar"] = "Tir à la corde",
                ["game.RpsMinusOne"] = "Pierre-papier-ciseaux moins un",
                ["game.JumpRope"] = "Corde à sauter mortelle",
                ["game.Boomerang"] = "Bagarre de boomerangs",
                ["game.Dodgeball"] = "Ballon prisonnier",
                ["game.MusicalChairs"] = "Chaises musicales",
                ["game.PresentSwap"] = "Sabotage du Père Noël secret",
                ["game.PropHunt"] = "Chasse aux objets",
                ["game.ChutesAndLadders"] = "Serpents et échelles",
                ["game.SimonSays"] = "Jacques a dit",
                ["game.KeepyUppy"] = "Garde le ballon",
                ["game.KingOfTheHill"] = "Roi des îles de lave",

                // ── UI chrome / navigation ──
                ["ui.back"] = "← Retour",
                ["ui.play"] = "JOUER",
                ["ui.your_player"] = "Ton joueur",
                ["ui.choose_how"] = "CHOISIS TON MODE",
                ["ui.play_online"] = "Jouer en ligne",
                ["ui.solo_vs_bots"] = "Solo contre des bots",
                ["ui.local_coop_n"] = "Coop local — {0} joueurs",
                ["ui.coop_needs_gamepad"] = "* Le coop local nécessite une manette branchée",
                ["ui.choose_difficulty"] = "{0}  ·  CHOISIS LA DIFFICULTÉ",
                ["ui.casual"] = "Décontracté",
                ["ui.hardcore"] = "Difficile",
                ["ui.save"] = "Enregistrer",
                ["ui.saved"] = "Enregistré",
                ["nav.leaderboard"] = "Classement",
                ["nav.how_to_play"] = "Comment jouer",
                ["nav.patch_notes"] = "Notes de version",

                // ── Settings ──
                ["set.language"] = "Langue :",
                ["set.colorblind"] = "Mode daltonien :",
                ["set.subtitles"] = "Légendes / sous-titres",
                ["set.reduce_motion"] = "Réduire les flashs et les secousses",
                ["set.master_volume"] = "Volume général : {0}%",
                ["set.game_volume"] = "Sons du jeu : {0}%",
                ["set.music_volume"] = "Musique de fond : {0}%",
                ["set.music"] = "Musique",
                ["set.remap"] = "Reconfigurer les commandes",
                ["set.credits"] = "Crédits et licences",
                ["cb.Normal"] = "Désactivé",
                ["cb.RedGreen"] = "Rouge–Vert",
                ["cb.BlueYellow"] = "Bleu–Jaune",

                // ── Results / HUD ──
                ["res.safe"] = "SAUF",
                ["res.out"] = "ÉLIMINÉ",
                ["res.you"] = "(TOI)",
                ["hud.countdown"] = "3 · 2 · 1 · PARTEZ !",
                ["hud.round_game"] = "Manche {0} · {1}",
                ["hud.players_alive"] = "Joueurs en vie : {0}",
                ["hud.hint_default"] = "ZQSD/Flèches pour te déplacer.",
                ["hud.hint_redlight"] = "Avance au VERT (ZQSD/Flèches). FIGE-TOI au ROUGE.",
                ["hud.hint_tug"] = "MARTÈLE Espace / Clic pour tirer ton équipe vers la victoire !",
                ["hud.hint_boomerang"] = "Bouger (ZQSD) · Viser (souris) · Lancer (Clic/Espace) · Dash (Maj)",
                ["hud.hint_move_action"] = "ZQSD/Flèches bouger · Espace action · Maj dash",
                ["hud.hint_glass"] = "À ton tour : ↑/↓ (ou W/S), ou touche HAUT / BAS, pour choisir une dalle.",
                ["hud.hint_chutes"] = "ESPACE pour lancer · ← / → pour choisir un embranchement.",
                ["hud.hint_jumprope"] = "ESPACE / Clic pour SAUTER la corde.",
                ["hud.hint_simon"] = "Obéis : W=tête A=nez S=clin d'œil D=pirouette Espace=saut · FIGE-TOI = ne touche à rien.",
                ["hud.hint_rps"] = "Duel pierre-papier-ciseaux (assisté par des bots dans cette version).",
                ["hud.hint_present"] = "Père Noël secret — deviner est assisté par des bots dans cette version.",

                // ── Per-game HUD status banners (DrawGameSpecific) ──
                ["hud.rl_red_freeze"] = "ROUGE — FIGE-TOI !",
                ["hud.rl_red"] = "ROUGE…",
                ["hud.rl_green"] = "VERT — VAS-Y !",
                ["hud.time"] = "Temps :",
                ["hud.survive"] = "Survis :",
                ["hud.left"] = "restantes",
                ["hud.deep_freeze"] = "GEL PROFOND !",
                ["hud.team_a"] = "Équipe A",
                ["hud.team_b"] = "Équipe B",
                ["hud.alive"] = "En vie :",
                ["hud.lava"] = "le sol est de la lave !",
                ["hud.round_lc"] = "manche",
                ["hud.psych"] = "…RATÉ ! continue de bouger",
                ["hud.group_of"] = "GROUPE DE",
                ["hud.mingle_wait"] = "Mêle-toi…",
                ["hud.row"] = "Rangée",
                ["hud.picks"] = "choisit…",
                ["hud.swing"] = "Tour",
                ["hud.bridge"] = "pont",
                ["hud.planks"] = "planches",
                ["hud.simon_freeze_banner"] = "FIGE-TOI — ne touche à rien !",
                ["hud.simon_banner"] = "JACQUES A DIT :",
                ["hud.beat"] = "Mesure",
                ["hud.simon_press"] = "appuie sur W/A/S/D/Espace",
                ["hud.race_top"] = "Cours vers le sommet !",
                ["hud.space_roll"] = "Espace pour lancer",
                ["hud.lights_out"] = "Lumières éteintes…",
                ["hud.guess_giver"] = "Devine ton donneur !",
                ["hud.reveal"] = "Révélation",
                ["hud.disguise"] = "Déguise-toi !",
                ["hud.found"] = "Trouvés",
                ["hud.hiding"] = "cachés",
                ["hud.dont_drop"] = "ne le laisse pas tomber !",

                // ── Online / lobby ──
                ["online.title"] = "Jouer en ligne",
                ["online.subtitle"] = "Crée un salon ou rejoins un ami avec un code. Les bots comblent les places vides.",
                ["online.server"] = "SERVEUR",
                ["online.connecting"] = "Connexion…",
                ["online.connect"] = "Se connecter",
                ["online.cant_reach"] = "Impossible de joindre le serveur.",
                ["online.dev_hint"] = "Lance le serveur de dev avec :  dotnet run --project server/Eliminated.Server -- 8080",
                ["online.host_room"] = "CRÉER UN SALON",
                ["online.difficulty"] = "Difficulté : {0}",
                ["online.create_room"] = "Créer un salon",
                ["online.join_by_code"] = "REJOINDRE PAR CODE",
                ["online.join"] = "Rejoindre",
                ["online.disconnect"] = "Se déconnecter",
                ["online.room_code"] = "CODE DU SALON",
                ["online.players"] = "JOUEURS ({0})",
                ["online.bot"] = "bot",
                ["online.you"] = "toi",
                ["online.add_bot"] = "Ajouter un bot",
                ["online.start_series"] = "Lancer la série",
                ["online.waiting_host"] = "En attente du lancement par l'hôte…",
                ["online.leave"] = "Quitter",

                // ── Game-Master captions (subtitles) ──
                ["gm.eliminated_you"] = "Tu as été éliminé !",
                ["gm.eliminated_one"] = "{0} a été éliminé.",
                ["gm.eliminated_many"] = "{0} joueurs éliminés.",
                ["gm.red_light"] = "FEU ROUGE — fige-toi !",
                ["gm.green_light"] = "FEU VERT — fonce !",
                ["gm.simon_says"] = "Jacques a dit : {0}",
                ["gm.simon_freeze"] = "Jacques a dit : FIGE-TOI — ne touche à rien !",
                ["simon.head"] = "touche ta tête",
                ["simon.nose"] = "touche ton nez",
                ["simon.blink"] = "cligne des yeux",
                ["simon.flip"] = "fais une pirouette",
                ["simon.jump"] = "saute",

                // ── Controls page + account toasts ──
                ["ctrl.keyboard_p1"] = "CLAVIER — JOUEUR 1",
                ["ctrl.press_key"] = "Appuie sur une touche…",
                ["ctrl.arrows_note"] = "Les flèches te déplacent toujours — impossible de les réassigner.",
                ["ctrl.reset"] = "Réinitialiser",
                ["ctrl.move_up"] = "Aller en haut",
                ["ctrl.move_down"] = "Aller en bas",
                ["ctrl.move_left"] = "Aller à gauche",
                ["ctrl.move_right"] = "Aller à droite",
                ["ctrl.action"] = "Action / Confirmer",
                ["ctrl.dash"] = "Dash",
                ["acct.saved_as"] = "Enregistré sous {0}",
                ["acct.enter_name"] = "Entre d'abord un nom",

                // ── MenuContent flavor copy (Landing / info pages) ──
                ["menu.tagline"] = "Des jeux d'enfance bon enfant. Des enjeux catastrophiques.",
                ["menu.hero_blurb"] = "D'adorables petits joueurs qui, franchement, ont signé un truc sans le lire. Le dernier joueur debout garde les Billes ◍ et le droit de se vanter ; les autres gardent la boîte.",
                ["menu.footer"] = "Amène des amis à trahir — ou remplis le salon de bots à blâmer.",
                ["menu.lb_title"] = "Mur des Survivants",
                ["menu.lb_subtitle"] = "Classés selon le total de Billes ◍ amassées sur le dos des défunts. Les défunts ne sont pas classés. Les défunts sont du compost.",
                ["menu.lb_empty"] = "Pas encore de champions. Le tableau est aussi vide que la conscience des organisateurs. Sois le premier à survivre !",
                ["menu.htp_title"] = "Comment jouer",
                ["menu.htp_subtitle"] = "…et, statistiquement, comment mourir.",
                ["menu.htp_intro"] = "Éliminé est un gentil jeu de fête pour 2 à 8 joueurs, dans le sens où tu arrives avec des amis et repars avec moins. Le Maître du Jeu enchaîne une série mystère de jeux d'enfance bien-aimés, chacun doté d'un bilan de victimes. Survis à tout le monde. Réussis un jeu et tu avances ; perds-en un et ton joueur est scellé dans une élégante boîte à ruban rose pendant que la foule applaudit quand même.",
                ["menu.hardcore_rule"] = "Difficile : si tu es éliminé, ton joueur est mort pour toute la série — tu regardes le reste depuis le confort de l'au-delà. Le dernier joueur debout est couronné champion. Et mourir, c'est finir fauché : les éliminés repartent avec zéro Bille ◍, seul le survivant encaisse la partie. Ta seule chance de toucher quelque chose depuis la tombe, c'est la Cagnotte des Morts — mise tes Billes épargnées sur le vainqueur. Pas de réapparition, pas de reprise, pas de RH.",
                ["menu.casual_rule"] = "Décontracté : les éliminations ne te coûtent que la manche — tout le monde réapparaît pour le jeu suivant, oubliant brièvement l'horreur. Le plus de points sur la série l'emporte, et chacun empoche des Billes ◍ selon son classement final, même les sortis tôt. La facture du psy est la même.",
                ["menu.patch_title"] = "Notes de version",
                ["menu.patch_subtitle"] = "une confession continue de tout ce qu'on a changé et cassé.",
                ["menu.account_title"] = "Ton joueur",
                ["menu.account_guest"] = "Garde tes Billes, couronnes et joueurs débloqués sur tous tes appareils. Les invités perdent tout quand la machine les oublie — comme les organisateurs oublient les noms.",
                ["menu.account_steam"] = "Steam se souvient de toi. Il se souvient de tout.",
                ["menu.controls_title"] = "Commandes",
                ["menu.controls_subtitle"] = "Reconfigure les touches vers une mort plus digne. Les flèches te déplacent toujours, quoi qu'il arrive.",
                ["menu.credits_title"] = "Crédits et licences",
                ["menu.credits_subtitle"] = "Les joueurs sont à nous. Presque tout le reste a été créé par des gens assez gentils pour le partager.",
                ["menu.credits_audio"] = "Son",
                ["menu.credits_art"] = "Art et modèles",
                ["menu.credits_music"] = "Musique",
                ["menu.back_htp"] = "Ça ne va nulle part ; toi non plus.",
                ["menu.back_patch"] = "Le prochain patch est toujours un nerf qui te vise personnellement.",
                ["menu.tier_last"] = "Le Dernier Joueur Debout",
                ["menu.tier_seasoned"] = "Survivant Aguerri",
                ["menu.tier_mid"] = "Menace de Seconde Zone",
                ["menu.tier_fodder"] = "Chair à Canon",
                ["menu.tier_compost"] = "À Peine du Compost",
                ["menu.tier_fresh"] = "Chair Fraîche",

                // ── Per-game guides (How to Play) ──
                ["guide.RedLight.tagline"] = "Avance au vert. Fige-toi au rouge. La Poupée ne fait pas d'avertissements.",
                ["guide.RedLight.rules"] = "Atteins la ligne d'arrivée. Pendant que la Poupée regarde (ROUGE), tout mouvement est fatal. Ne bouge qu'au VERT. Elle n'accepte aucun appel.",
                ["guide.RedLight.controls"] = "ZQSD / ↑ avance (ou glisse). A·D esquive entre les voies. FIGE-TOI dès que ça passe au ROUGE.",
                ["guide.RedLight.flavor"] = "Vert, tu y vas. Rouge, on a une discussion franche sur tes choix.",
                ["guide.Tag.tagline"] = "Le bleu chasse. Le rose fuit. Dégèle tes amis ou brise-toi au buzzer.",
                ["guide.Tag.rules"] = "🔵 Les geleurs BLEUS poursuivent les coureurs 🩷 ROSES — il suffit de bousculer un coureur pour le geler (pas de bouton, le contact suffit). Les ROSES libèrent un coéquipier gelé de la même façon. Au buzzer, tout ROSE encore gelé est éliminé — et tout BLEU n'ayant attrapé PERSONNE tombe aussi.",
                ["guide.Tag.controls"] = "Déplace-toi avec ZQSD / Flèches ou glisse — pas de bouton d'action, tu attrapes en bousculant. BLEU : gèle les coureurs. ROSE : fuis, et fonce sur un coéquipier gelé pour le DÉGELER.",
                ["guide.Tag.flavor"] = "Mains froides, indemnité de départ encore plus froide.",
                ["guide.Mingle.tagline"] = "Forme un groupe de la taille exacte. Fais-toi des amis ou fais-en ton deuil.",
                ["guide.Mingle.rules"] = "Tout le monde commence sur la plateforme tournante pendant que la musique joue. Quand elle S'ARRÊTE, un nombre apparaît — fonce dans un cercle en groupe d'EXACTEMENT ce nombre. Trop peu, trop nombreux, ou encore sur la plateforme ? Éliminé.",
                ["guide.Mingle.controls"] = "Déplace-toi avec ZQSD / Flèches ou glisse. Quand la musique s'arrête et qu'un nombre apparaît, entasse-toi dans un cercle en groupe de cette taille exacte.",
                ["guide.Mingle.flavor"] = "Trouve les tiens. Ils t'abandonneront sans hésiter.",
                ["guide.GlassBridge.tagline"] = "Une dalle tient. L'autre non. Parie avec tes pieds.",
                ["guide.GlassBridge.rules"] = "Un pont, un chemin sûr caché. Traversez UN PAR UN dans l'ordre de la file : le joueur de devant devine GAUCHE ou DROITE pour la dalle suivante. Mauvais choix, le verre se brise — tu es fini, mais tous ceux derrière voient désormais le bon côté.",
                ["guide.GlassBridge.controls"] = "À ton tour, appuie sur ← / → (ou A·D) pour choisir la dalle de GAUCHE ou de DROITE.",
                ["guide.GlassBridge.flavor"] = "C'est du cinquante-cinquante. La maison a déjà pris l'autre cinquante.",
                ["guide.TugOfWar.tagline"] = "Martèle pour tirer. L'équipe perdante teste la gravité.",
                ["guide.TugOfWar.rules"] = "Deux équipes. Martèle le bouton pour tirer la corde de ton côté. L'équipe traînée par-dessus le bord est éliminée. La gravité fait le reste.",
                ["guide.TugOfWar.controls"] = "MARTÈLE le bouton d'action (ou Espace / clic) aussi vite que possible !",
                ["guide.TugOfWar.flavor"] = "Oh hisse ! Dans le vide, les sous-performants.",
                ["guide.RpsMinusOne.tagline"] = "Lance-en deux. Lâches-en une. Sois plus malin qu'un inconnu ou meurs en essayant.",
                ["guide.RpsMinusOne.rules"] = "Affronte un adversaire. Choisis DEUX coups avant la fin du chrono, puis LÂCHES-en un — bats le minuteur ou tu DÉCLARES FORFAIT et tu es éliminé. Le pierre-feuille-ciseaux classique décide ; le perdant est éliminé. Une égalité, on rejoue.",
                ["guide.RpsMinusOne.controls"] = "Clique sur deux coups, puis sur celui à GARDER — bats le compte à rebours ou tu déclares forfait. Égalité = on rejoue, personne n'est éliminé.",
                ["guide.RpsMinusOne.flavor"] = "Pierre, feuille, ciseaux, moins un, plus des conséquences.",
                ["guide.JumpRope.tagline"] = "Saute à la corde pour traverser le pont. La corde est patiente. Pas toi.",
                ["guide.JumpRope.rules"] = "Une corde géante balaie un pont au-dessus d'un grand vide. Chaque SAUT propre te porte d'une planche de plus. Mauvais timing et tu es balayé par-dessus bord. Atteins l'autre côté pour être sauf — mais la corde ne fait qu'accélérer.",
                ["guide.JumpRope.controls"] = "Appuie sur ESPACE / clic / tape pour SAUTER la corde et traverser le pont.",
                ["guide.JumpRope.flavor"] = "Ce n'est pas la corde qui te tue. C'est la planche que tu n'atteins jamais.",
                ["guide.Boomerang.tagline"] = "Lance, esquive, attrape des bonus douteux. Dernier joueur debout.",
                ["guide.Boomerang.rules"] = "Une arène en chacun pour soi. Lance ton boomerang, esquive ceux qui arrivent et attrape des bonus délirants (environ la moitié te veulent mort). Le dernier joueur debout survit.",
                ["guide.Boomerang.controls"] = "Déplace-toi avec ZQSD / Flèches. Vise à la souris, clique pour LANCER. Dash avec Maj.",
                ["guide.Boomerang.flavor"] = "Tout va bien jusqu'à ce que ça revienne à l'expéditeur.",
                ["guide.Dodgeball.tagline"] = "Deux équipes, une ligne, une élégante grêle de caoutchouc. Dernière équipe debout.",
                ["guide.Dodgeball.rules"] = "Attrape une balle et lance-la de l'autre côté de la ligne. Quiconque est touché (sans bouclier) est ÉLIMINÉ. Dash pour esquiver. Anéantis l'autre équipe — ou aie simplement plus de joueurs au buzzer.",
                ["guide.Dodgeball.controls"] = "ZQSD déplacer · souris viser · clic / ESPACE lancer · MAJ dash pour esquiver.",
                ["guide.Dodgeball.flavor"] = "Esquive, baisse-toi, feinte, plonge et meurs.",
                ["guide.MusicalChairs.tagline"] = "Quand la musique s'arrête, attrape une chaise. Ou attrape un indice.",
                ["guide.MusicalChairs.rules"] = "Déambule pendant que la musique joue. Dès qu'elle S'ARRÊTE, fonce sur une chaise. Un joueur par chaise — quiconque reste debout est ÉLIMINÉ. Une chaise disparaît à chaque manche, parce que la rareté est le but.",
                ["guide.MusicalChairs.controls"] = "Déplace-toi avec ZQSD / Flèches ou glisse. Les chaises n'apparaissent que quand la musique S'ARRÊTE — alors fonce !",
                ["guide.MusicalChairs.flavor"] = "La musique te ment. Elle s'arrête toujours. Comme tout.",
                ["guide.PresentSwap.tagline"] = "Choisis une cible dans le noir. Devine ton donneur, ou paie le geste.",
                ["guide.PresentSwap.rules"] = "Quand les lumières s'éteignent, des DONNEURS secrets glissent chacun un cadeau au joueur de leur choix. Lumières allumées : si tu as reçu un cadeau, devine qui l'a donné — bonne réponse, le donneur est ÉLIMINÉ ; mauvaise réponse, c'est TOI qui sors. Donneurs : choisissez votre cible, puis restez cachés.",
                ["guide.PresentSwap.controls"] = "Donneur secret ? Tape un joueur pour lui offrir un cadeau pendant que les lumières sont éteintes. Reçu un cadeau ? Tape celui qui te l'a glissé selon toi.",
                ["guide.PresentSwap.flavor"] = "Quelqu'un t'a laissé un cadeau. Comme c'est attentionné. Comme c'est compromettant.",
                ["guide.PropHunt.tagline"] = "Deviens le mobilier. Un joueur a une épée et un quota.",
                ["guide.PropHunt.rules"] = "Chacun se déguise en objet aléatoire et se fond dans une pièce de leurres identiques. UN Chercheur rôde avec une lame — mais quelques coups seulement avant qu'elle s'émousse. Embroché, tu es mis en boîte ; reste parfaitement immobile et tu n'es qu'un tonneau.",
                ["guide.PropHunt.controls"] = "Cachés : ZQSD / Flèches pour avancer discrètement — mais RESTE IMMOBILE pour te fondre. Chercheur : déplace-toi + ESPACE / clic pour trancher l'objet le plus proche.",
                ["guide.PropHunt.flavor"] = "Si tu ne peux pas battre le décor, deviens le décor.",
                ["guide.ChutesAndLadders.tagline"] = "Grimpe les échelles. Parie sur les toboggans. Bats le chrono.",
                ["guide.ChutesAndLadders.rules"] = "FONCE vers le sommet (case 64) pour être SAUF. Les échelles te propulsent vers le haut. Tombe sur un TOBOGGAN et tu dois PARIER GAUCHE ou DROITE : un côté te renvoie au DÉPART, l'autre te jette dans l'ABÎME — éliminé. Les côtés d'un toboggan ne changent jamais, alors regarde qui tombe en premier.",
                ["guide.ChutesAndLadders.controls"] = "MARTÈLE pour LANCER (ou ESPACE). 🪜 grimpe · à un TOBOGGAN choisis ◀ GAUCHE / DROITE ▶ (A·D ou ←·→). Atteins 🏁 avant le chrono !",
                ["guide.ChutesAndLadders.flavor"] = "Les échelles donnent. Les toboggans te demandent de choisir ta propre perte. Le chrono, lui, se contente de rire.",
                ["guide.SimonSays.tagline"] = "Fais exactement ce qu'on te dit. Rate, bloque ou tressaille — et c'est fini.",
                ["guide.SimonSays.rules"] = "Le Maître du Jeu aboie un ordre — fais le bon mouvement avant la fin du minuteur. 🙌 tête · 👃 nez · 👀 cligne · 🤸 pirouette · ⬆️ saute. Sur 🧊 FIGE-TOI, ne touche à RIEN. Mauvais mouvement, trop lent, ou un seul tic nerveux : éliminé.",
                ["guide.SimonSays.controls"] = "W tête · A nez · S cligne · D pirouette · ESPACE saute — et FIGE-TOI veut dire mains IMMOBILES. (Suit tes réassignations.)",
                ["guide.SimonSays.flavor"] = "Jacques a dit d'obéir. Jacques n'a pas dit qu'il y avait un remboursement.",
                ["guide.KeepyUppy.tagline"] = "Garde ton ballon loin du sol. Crève celui des autres. Travail d'équipe !™",
                ["guide.KeepyUppy.rules"] = "Tu as un ballon à tes couleurs. Ne le laisse pas toucher le sol et ne le laisse pas crever — l'un ou l'autre et c'est fini. Tape-le pour le renvoyer en l'air ; SMASHE pour crever celui d'un rival. L'air devient de plus en plus lourd.",
                ["guide.KeepyUppy.controls"] = "ZQSD / Flèches ou glisse pour te placer sous ton ballon (tu le tapes automatiquement). ESPACE / clic pour crever celui d'un rival.",
                ["guide.KeepyUppy.flavor"] = "C'est un jeu de fête pour enfants. Les enfants sont partis. Les épingles restent.",
                ["guide.KingOfTheHill.tagline"] = "Le sol est de la lave. Les îles coulent. La couronne est mesquine.",
                ["guide.KingOfTheHill.rules"] = "Le sol est de la lave et les îles coulent une à une. Saute entre elles pour rester hors du sol, attrape des bonus et pousse les rivaux dans le magma. Les îles s'épuisent — le dernier joueur qui ne brûle pas est CHAMPION.",
                ["guide.KingOfTheHill.controls"] = "ZQSD / Flèches ou glisse pour sauter entre les îles qui coulent. Vise à la souris, puis CLIC / ESPACE pour POUSSER un rival dans la lave.",
                ["guide.KingOfTheHill.flavor"] = "Tous les trônes sont temporaires. Ceux-ci coulent en plus.",

                // ── Info pages: Account / How-to-Play / Players shop ──
                ["acct.col_player"] = "JOUEUR",
                ["acct.col_title"] = "TITRE",
                ["acct.col_crowns"] = "COURONNES",
                ["acct.steam_submit"] = "Tes billes sont envoyées aux classements Steam à la fin de chaque série.",
                ["acct.steam_global"] = "Les classements mondiaux sont sur Steam — lance via Steam et ton butin rejoint le Mur.",
                ["acct.everything"] = "Tout ce que tu as gagné, et tous ceux à qui tu as survécu.",
                ["acct.signed_in_steam"] = "Connecté via Steam",
                ["acct.display_name"] = "NOM AFFICHÉ",
                ["acct.guest"] = "Tu joues en joueur invité.",
                ["acct.stat_marbles"] = "◍ BILLES",
                ["acct.stat_crowns"] = "👑 COURONNES",
                ["acct.stat_rounds"] = "🩸 MANCHES",
                ["acct.stat_title"] = "🏷 TITRE",
                ["acct.steam_cloud"] = "Ton butin, tes couronnes et tes joueurs débloqués se synchronisent via Steam Cloud. Rien n'est oublié.",
                ["htp.the_games"] = "LES JEUX",
                ["htp.controls"] = "Commandes",
                ["htp.controls_caps"] = "COMMANDES",
                ["htp.live_bots"] = "EN DIRECT • bots",
                ["shop.choose_player"] = "Choisis ton joueur",
                ["shop.player_hint"] = "Touche pour le porter. Les joueurs verrouillés coûtent des Billes ◍, gagnées honnêtement en survivant à tes amis.",
                ["shop.wearing"] = "TU JOUES :",
                ["shop.tab_players"] = "Joueurs",
                ["shop.tab_acc"] = "Accessoires",
                ["shop.cant_draw"] = "Impossible d'afficher la garde-robe :",
                ["shop.selected"] = "SÉLECTIONNÉ",
                ["shop.tap_wear"] = "Touche pour le porter",
                ["shop.worn_remove"] = "PORTÉ — touche pour retirer",
                ["shop.slot_hats"] = "🎩  CHAPEAUX",
                ["shop.slot_eyewear"] = "👓  LUNETTES",
                ["shop.slot_neck"] = "🧣  TOUR DE COU",
                ["shop.slot_ear"] = "🌼  DERRIÈRE L'OREILLE",
            },
            // de / pt-BR / ja: localize the most visible strings; the rest falls back to English.
            ["de"] = new Dictionary<string, string>
            {
                ["ui.title"] = "ELIMINIERT",
                ["ui.settings"] = "Einstellungen",
                ["ui.quit"] = "Beenden",
                ["ui.back_to_menu"] = "Zurück zum Menü",
                ["ui.local_coop"] = "Lokaler Koop",
                ["ui.series_over"] = "Ein Gewinner Steht Fest",
                ["game.RedLight"] = "Rotlicht, Grünlicht",
                ["game.TugOfWar"] = "Tauziehen",
                ["game.Dodgeball"] = "Völkerball",
                ["game.MusicalChairs"] = "Reise nach Jerusalem",
                ["game.KingOfTheHill"] = "König der Lavainseln",
                ["ui.back"] = "← Zurück",
                ["ui.play"] = "SPIELEN",
                ["ui.your_player"] = "Dein Spieler",
                ["ui.choose_how"] = "WÄHLE DEINEN MODUS",
                ["ui.play_online"] = "Online spielen",
                ["ui.solo_vs_bots"] = "Solo gegen Bots",
                ["ui.choose_difficulty"] = "{0}  ·  SCHWIERIGKEIT WÄHLEN",
                ["ui.casual"] = "Locker",
                ["ui.hardcore"] = "Hardcore",
                ["ui.save"] = "Speichern",
                ["ui.saved"] = "Gespeichert",
                ["nav.leaderboard"] = "Bestenliste",
                ["nav.how_to_play"] = "Spielanleitung",
                ["nav.patch_notes"] = "Patch-Notes",
                ["set.language"] = "Sprache:",
                ["set.colorblind"] = "Farbenblind-Modus:",
                ["set.subtitles"] = "Bildunterschriften / Untertitel",
                ["set.reduce_motion"] = "Blinken & Bildschirmwackeln reduzieren",
                ["set.master_volume"] = "Gesamtlautstärke: {0}%",
                ["set.music"] = "Musik",
                ["set.remap"] = "Steuerung neu belegen",
                ["set.credits"] = "Credits & Lizenzen",
                ["cb.Normal"] = "Aus",
                ["cb.RedGreen"] = "Rot–Grün",
                ["cb.BlueYellow"] = "Blau–Gelb",
                ["res.safe"] = "SICHER",
                ["res.out"] = "RAUS",
                ["res.you"] = "(DU)",
                ["hud.countdown"] = "3 · 2 · 1 · LOS!",
                ["hud.round_game"] = "Runde {0} · {1}",
                ["hud.players_alive"] = "Spieler am Leben: {0}",
                ["online.title"] = "Online spielen",
                ["online.connect"] = "Verbinden",
                ["online.create_room"] = "Raum erstellen",
                ["online.join"] = "Beitreten",
                ["online.leave"] = "Verlassen",
                ["online.start_series"] = "Serie starten",
                ["online.add_bot"] = "Bot hinzufügen",
                ["online.waiting_host"] = "Warte auf den Host…",
                ["gm.eliminated_you"] = "Du wurdest eliminiert!",
                ["gm.eliminated_one"] = "{0} wurde eliminiert.",
                ["gm.eliminated_many"] = "{0} Spieler eliminiert.",
                ["gm.red_light"] = "ROT — einfrieren!",
                ["gm.green_light"] = "GRÜN — los!",
            },
            ["pt-BR"] = new Dictionary<string, string>
            {
                ["ui.title"] = "ELIMINADO",
                ["ui.settings"] = "Configurações",
                ["ui.quit"] = "Sair",
                ["ui.back_to_menu"] = "Voltar ao menu",
                ["ui.local_coop"] = "Coop local",
                ["ui.series_over"] = "Um Vencedor Foi Decidido",
                ["game.RedLight"] = "Batatinha frita 1, 2, 3",
                ["game.TugOfWar"] = "Cabo de guerra",
                ["game.Dodgeball"] = "Queimada",
                ["game.MusicalChairs"] = "Dança das cadeiras",
                ["game.KingOfTheHill"] = "Rei das ilhas de lava",
                ["ui.back"] = "← Voltar",
                ["ui.play"] = "JOGAR",
                ["ui.your_player"] = "Seu jogador",
                ["ui.choose_how"] = "ESCOLHA COMO JOGAR",
                ["ui.play_online"] = "Jogar online",
                ["ui.solo_vs_bots"] = "Solo vs Bots",
                ["ui.choose_difficulty"] = "{0}  ·  ESCOLHA A DIFICULDADE",
                ["ui.casual"] = "Casual",
                ["ui.hardcore"] = "Hardcore",
                ["ui.save"] = "Salvar",
                ["ui.saved"] = "Salvo",
                ["nav.leaderboard"] = "Ranking",
                ["nav.how_to_play"] = "Como jogar",
                ["nav.patch_notes"] = "Notas de atualização",
                ["set.language"] = "Idioma:",
                ["set.colorblind"] = "Modo daltônico:",
                ["set.subtitles"] = "Legendas",
                ["set.reduce_motion"] = "Reduzir flashes e tremor de tela",
                ["set.master_volume"] = "Volume geral: {0}%",
                ["set.music"] = "Música",
                ["set.remap"] = "Remapear controles",
                ["set.credits"] = "Créditos e licenças",
                ["cb.Normal"] = "Desligado",
                ["cb.RedGreen"] = "Vermelho–Verde",
                ["cb.BlueYellow"] = "Azul–Amarelo",
                ["res.safe"] = "A SALVO",
                ["res.out"] = "FORA",
                ["res.you"] = "(VOCÊ)",
                ["hud.countdown"] = "3 · 2 · 1 · JÁ!",
                ["hud.round_game"] = "Rodada {0} · {1}",
                ["hud.players_alive"] = "Jogadores vivos: {0}",
                ["online.title"] = "Jogar online",
                ["online.connect"] = "Conectar",
                ["online.create_room"] = "Criar sala",
                ["online.join"] = "Entrar",
                ["online.leave"] = "Sair",
                ["online.start_series"] = "Iniciar série",
                ["online.add_bot"] = "Adicionar bot",
                ["online.waiting_host"] = "Aguardando o anfitrião começar…",
                ["gm.eliminated_you"] = "Você foi eliminado!",
                ["gm.eliminated_one"] = "{0} foi eliminado.",
                ["gm.eliminated_many"] = "{0} jogadores eliminados.",
                ["gm.red_light"] = "VERMELHO — congele!",
                ["gm.green_light"] = "VERDE — vai!",
            },
            ["ja"] = new Dictionary<string, string>
            {
                ["ui.title"] = "イリミネイテッド",
                ["ui.settings"] = "設定",
                ["ui.quit"] = "やめる",
                ["ui.back_to_menu"] = "メニューに戻る",
                ["ui.local_coop"] = "ローカル協力プレイ",
                ["ui.series_over"] = "勝者が決定しました",
                ["game.RedLight"] = "だるまさんがころんだ",
                ["game.TugOfWar"] = "綱引き",
                ["game.Dodgeball"] = "ドッジボール",
                ["game.MusicalChairs"] = "イス取りゲーム",
                ["game.KingOfTheHill"] = "溶岩島の王",
                ["ui.back"] = "← 戻る",
                ["ui.play"] = "プレイ",
                ["ui.your_player"] = "あなたのプレイヤー",
                ["ui.choose_how"] = "プレイ方法を選ぶ",
                ["ui.play_online"] = "オンラインで遊ぶ",
                ["ui.solo_vs_bots"] = "ソロ vs ボット",
                ["ui.choose_difficulty"] = "{0}  ·  難易度を選ぶ",
                ["ui.casual"] = "カジュアル",
                ["ui.hardcore"] = "ハードコア",
                ["ui.save"] = "保存",
                ["ui.saved"] = "保存しました",
                ["nav.leaderboard"] = "ランキング",
                ["nav.how_to_play"] = "遊び方",
                ["nav.patch_notes"] = "パッチノート",
                ["set.language"] = "言語：",
                ["set.colorblind"] = "色覚モード：",
                ["set.subtitles"] = "キャプション・字幕",
                ["set.reduce_motion"] = "点滅と画面の揺れを抑える",
                ["set.master_volume"] = "全体の音量：{0}%",
                ["set.music"] = "音楽",
                ["set.remap"] = "操作の再設定",
                ["set.credits"] = "クレジットとライセンス",
                ["cb.Normal"] = "オフ",
                ["cb.RedGreen"] = "赤緑（1・2型）",
                ["cb.BlueYellow"] = "青黄（3型）",
                ["res.safe"] = "セーフ",
                ["res.out"] = "アウト",
                ["res.you"] = "（あなた）",
                ["hud.countdown"] = "3 · 2 · 1 · スタート！",
                ["hud.round_game"] = "ラウンド {0} · {1}",
                ["hud.players_alive"] = "生存プレイヤー：{0}",
                ["online.title"] = "オンラインで遊ぶ",
                ["online.connect"] = "接続",
                ["online.create_room"] = "ルーム作成",
                ["online.join"] = "参加",
                ["online.leave"] = "退出",
                ["online.start_series"] = "シリーズ開始",
                ["online.add_bot"] = "ボットを追加",
                ["online.waiting_host"] = "ホストの開始を待っています…",
                ["gm.eliminated_you"] = "あなたは脱落しました！",
                ["gm.eliminated_one"] = "{0} が脱落しました。",
                ["gm.eliminated_many"] = "{0} 体のプレイヤーが脱落しました。",
                ["gm.red_light"] = "赤 — 止まれ！",
                ["gm.green_light"] = "青 — 進め！",
            },
            // Korean — the genre this game homages is Korean, so the childhood-game
            // names use their real Korean equivalents (e.g. 무궁화 꽃이 피었습니다).
            ["ko"] = new Dictionary<string, string>
            {
                ["ui.title"] = "일리미네이티드",
                ["ui.settings"] = "설정",
                ["ui.quit"] = "종료",
                ["ui.back_to_menu"] = "메뉴로 돌아가기",
                ["ui.local_coop"] = "로컬 협동",
                ["ui.series_over"] = "우승자가 결정되었습니다",
                ["game.RedLight"] = "무궁화 꽃이 피었습니다",
                ["game.TugOfWar"] = "줄다리기",
                ["game.Dodgeball"] = "피구",
                ["game.MusicalChairs"] = "의자 앉기 게임",
                ["game.KingOfTheHill"] = "용암 섬의 왕",
                ["ui.back"] = "← 뒤로",
                ["ui.play"] = "플레이",
                ["ui.your_player"] = "내 플레이어",
                ["ui.choose_how"] = "플레이 방식 선택",
                ["ui.play_online"] = "온라인 플레이",
                ["ui.solo_vs_bots"] = "솔로 vs 봇",
                ["ui.choose_difficulty"] = "{0}  ·  난이도 선택",
                ["ui.casual"] = "캐주얼",
                ["ui.hardcore"] = "하드코어",
                ["ui.save"] = "저장",
                ["ui.saved"] = "저장됨",
                ["nav.leaderboard"] = "순위표",
                ["nav.how_to_play"] = "플레이 방법",
                ["nav.patch_notes"] = "패치 노트",
                ["set.language"] = "언어:",
                ["set.colorblind"] = "색맹 모드:",
                ["set.subtitles"] = "자막",
                ["set.reduce_motion"] = "번쩍임 및 화면 흔들림 줄이기",
                ["set.master_volume"] = "전체 음량: {0}%",
                ["set.music"] = "음악",
                ["set.remap"] = "조작키 재설정",
                ["cb.Normal"] = "끄기",
                ["cb.RedGreen"] = "적·녹",
                ["cb.BlueYellow"] = "청·황",
                ["res.safe"] = "합격",
                ["res.out"] = "탈락",
                ["res.you"] = "(나)",
                ["hud.countdown"] = "3 · 2 · 1 · 시작!",
                ["hud.round_game"] = "라운드 {0} · {1}",
                ["hud.players_alive"] = "생존 플레이어: {0}",
                ["online.title"] = "온라인 플레이",
                ["online.connect"] = "연결",
                ["online.create_room"] = "방 만들기",
                ["online.join"] = "참가",
                ["online.leave"] = "나가기",
                ["online.start_series"] = "시리즈 시작",
                ["online.add_bot"] = "봇 추가",
                ["online.waiting_host"] = "방장이 시작하기를 기다리는 중…",
                ["gm.eliminated_you"] = "당신은 탈락했습니다!",
                ["gm.eliminated_one"] = "{0} 탈락.",
                ["gm.eliminated_many"] = "{0}명의 플레이어가 탈락했습니다.",
                ["gm.red_light"] = "빨간불 — 멈춰!",
                ["gm.green_light"] = "초록불 — 가!",
            },
            // Simplified Chinese — childhood-game names use their real Chinese
            // equivalents (e.g. 一二三木头人 for Red Light, Green Light).
            ["zh-Hans"] = new Dictionary<string, string>
            {
                ["ui.title"] = "淘汰",
                ["ui.settings"] = "设置",
                ["ui.quit"] = "退出",
                ["ui.back_to_menu"] = "返回菜单",
                ["ui.local_coop"] = "本地合作",
                ["ui.series_over"] = "胜者已决出",
                ["game.RedLight"] = "一二三木头人",
                ["game.TugOfWar"] = "拔河",
                ["game.Dodgeball"] = "躲避球",
                ["game.MusicalChairs"] = "抢椅子",
                ["game.KingOfTheHill"] = "熔岩岛之王",
                ["ui.back"] = "← 返回",
                ["ui.play"] = "开始",
                ["ui.your_player"] = "你的玩家",
                ["ui.choose_how"] = "选择玩法",
                ["ui.play_online"] = "在线游玩",
                ["ui.solo_vs_bots"] = "单人 vs 机器人",
                ["ui.choose_difficulty"] = "{0}  ·  选择难度",
                ["ui.casual"] = "休闲",
                ["ui.hardcore"] = "硬核",
                ["ui.save"] = "保存",
                ["ui.saved"] = "已保存",
                ["nav.leaderboard"] = "排行榜",
                ["nav.how_to_play"] = "游戏玩法",
                ["nav.patch_notes"] = "更新日志",
                ["set.language"] = "语言：",
                ["set.colorblind"] = "色盲模式：",
                ["set.subtitles"] = "字幕",
                ["set.reduce_motion"] = "减少闪烁和屏幕震动",
                ["set.master_volume"] = "主音量：{0}%",
                ["set.music"] = "音乐",
                ["set.remap"] = "重新映射控制",
                ["cb.Normal"] = "关闭",
                ["cb.RedGreen"] = "红绿",
                ["cb.BlueYellow"] = "蓝黄",
                ["res.safe"] = "晋级",
                ["res.out"] = "淘汰",
                ["res.you"] = "（你）",
                ["hud.countdown"] = "3 · 2 · 1 · 开始！",
                ["hud.round_game"] = "第 {0} 回合 · {1}",
                ["hud.players_alive"] = "存活玩家：{0}",
                ["online.title"] = "在线游玩",
                ["online.connect"] = "连接",
                ["online.create_room"] = "创建房间",
                ["online.join"] = "加入",
                ["online.leave"] = "离开",
                ["online.start_series"] = "开始系列赛",
                ["online.add_bot"] = "添加机器人",
                ["online.waiting_host"] = "等待房主开始…",
                ["gm.eliminated_you"] = "你被淘汰了！",
                ["gm.eliminated_one"] = "{0} 被淘汰。",
                ["gm.eliminated_many"] = "{0} 个玩家被淘汰。",
                ["gm.red_light"] = "红灯 — 停！",
                ["gm.green_light"] = "绿灯 — 走！",
            },
        };
    }
}
