using System;
using System.Globalization;
using System.IO;
using System.Text;

namespace Eliminated.Tools.ModelGen
{
    /// <summary>
    /// Generates a "player" character mesh as a Wavefront OBJ (our own procedural
    /// geometry — no third-party license). A UV sphere squashed and rounded into a
    /// cute player silhouette. Unity imports OBJ natively, so this is a real,
    /// importable 3D model the client can use in place of the placeholder sphere.
    /// </summary>
    public static class Program
    {
        private const int Rings = 24;     // latitude divisions
        private const int Segments = 32;   // longitude divisions

        public static void Main(string[] args)
        {
            string outDir = args.Length > 0
                ? args[0]
                : Path.Combine("..", "..", "unity", "EliminatedGame", "Assets", "Eliminated", "Resources", "Models");
            Directory.CreateDirectory(outDir);

            string path = Path.Combine(outDir, "player.obj");
            File.WriteAllText(path, BuildPlayer());
            Console.WriteLine($"  wrote {Path.GetFileName(path)}");

            using (var sw = new StreamWriter(Path.Combine(outDir, "MODEL_MANIFEST.md")))
            {
                sw.WriteLine("# Generated 3D models (our own procedural geometry, no third-party license)");
                sw.WriteLine();
                sw.WriteLine("Produced by `tools/ModelGen`. Wavefront OBJ; Unity imports natively.");
                sw.WriteLine($"- `player.obj` — player character mesh ({Rings}x{Segments} UV sphere, squashed).");
            }
            Console.WriteLine($"Generated player model into {outDir}");
        }

        private static string BuildPlayer()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Eliminated player — generated by tools/ModelGen (CC0 / our own output)");
            sb.AppendLine("o Player");

            var verts = new System.Collections.Generic.List<(float x, float y, float z)>();
            var norms = new System.Collections.Generic.List<(float x, float y, float z)>();

            for (int r = 0; r <= Rings; r++)
            {
                float v = r / (float)Rings;             // 0..1 top->bottom
                float phi = v * MathF.PI;               // 0..pi
                float sy = MathF.Cos(phi);              // 1..-1
                float sr = MathF.Sin(phi);              // radius at this ring

                // Player shaping: squash vertically, fatten the lower body, round the base.
                float y = sy * 0.82f + 0.12f;           // squashed + lifted so it sits on the floor
                float bulge = 1f + 0.18f * MathF.Sin(phi);          // widest around the middle-low
                float taper = 0.85f + 0.15f * (1f - v);            // slightly narrower on top
                float radius = sr * bulge * taper;

                for (int s = 0; s <= Segments; s++)
                {
                    float u = s / (float)Segments;
                    float theta = u * MathF.PI * 2f;
                    float x = MathF.Cos(theta) * radius;
                    float z = MathF.Sin(theta) * radius;
                    verts.Add((x, y, z));
                    var n = Normalize(x, y * 1.2f, z);
                    norms.Add(n);
                }
            }

            foreach (var p in verts) sb.AppendLine($"v {F(p.x)} {F(p.y)} {F(p.z)}");
            foreach (var n in norms) sb.AppendLine($"vn {F(n.x)} {F(n.y)} {F(n.z)}");

            int stride = Segments + 1;
            for (int r = 0; r < Rings; r++)
            {
                for (int s = 0; s < Segments; s++)
                {
                    int a = r * stride + s + 1;          // OBJ is 1-indexed
                    int b = a + 1;
                    int c = a + stride;
                    int d = c + 1;
                    // two triangles per quad, with matching normals
                    sb.AppendLine($"f {a}//{a} {c}//{c} {b}//{b}");
                    sb.AppendLine($"f {b}//{b} {c}//{c} {d}//{d}");
                }
            }
            return sb.ToString();
        }

        private static (float, float, float) Normalize(float x, float y, float z)
        {
            float m = MathF.Sqrt(x * x + y * y + z * z);
            if (m < 1e-6f) return (0, 1, 0);
            return (x / m, y / m, z / m);
        }

        private static string F(float v) => v.ToString("0.#####", CultureInfo.InvariantCulture);
    }
}
